### ISSUE TITLE
[Bug]: got an unexpected keyword argument 'ddim_steps'

### ISSUE THREAD

**Issue by GlasslessPizza** [sd-webui/stable-diffusion-webui#1007]
### What happened?

I run this repo from command line.
This is the command from inside this conda env I'm using:
```
python optimizedSD/optimized_txt2img.py --prompt "castle in the sky by monet"
```
which results in a `TypeError: __init__() got an unexpected keyword argument 'ddim_steps'`
(full log below).

I think I installed the repo correctly, same procedure as other repos that work just fine.

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Custom settings

```shell
python optimizedSD/optimized_txt2img.py --prompt "castle in the sky by monet"
```

### Relevant log output

```shell
Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
Traceback (most recent call last):
  File "optimizedSD/optimized_txt2img.py", line 192, in <module>
    model = instantiate_from_config(config.modelUNet)
  File "c:\stable-diffusion\stable-diffusion-webui-master\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "c:\stable-diffusion\stable-diffusion-webui-master\optimizedSD\ddpm.py", line 348, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ddim_steps'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
Is optimizedSD even still up-to-date? Hope folks who contributed it will chime in.
In the meantime I suggest you use the official entry points: webui.py or webui_streamlit.py or launch via provided cmd files.
