### ISSUE TITLE
[Bug]: img2img couldn't find session

### ISSUE THREAD

**Issue by ExiaCyn** [sd-webui/stable-diffusion-webui#1037]
### What happened?

I've loaded an image and set parameters however when I goto generate from the prompt I get no output. When you hit refresh the command prompt shows;

Couldn't find session "f115d308aca64074942b7f224a55f5e9" for call to FuncKey(job_id=UUID('c5517c44-9530-4d65-abb8-a453be7e78c6'), func=<function img2img at 0x0000023535097CA0>)

I've tried this with different image inputs and in both crop and mask mode but no change. The normal Text - Image prompt works just fine.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Couldn't find session "f115d308aca64074942b7f224a55f5e9" for call to FuncKey(job_id=UUID('c5517c44-9530-4d65-abb8-a453be7e78c6'), func=<function img2img at 0x0000023535097CA0>)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SphaeroX** [comment]
the same here at text to image.

it looks like the web ui has already canceled the job, but in the UI itself it hasn't been marked as canceled yet. therefore it doesn't fidnet a job to cancel anymore.

![Screenshot 2022-09-19 102330](https://user-images.githubusercontent.com/6785110/190977376-d25c6ca4-7c3b-4209-b514-16da725adfb3.jpg)
