### ISSUE TITLE
[Bug]: model slowdown

### ISSUE THREAD

**Issue by endomorphosis** [sd-webui/stable-diffusion-webui#1053]
### What happened?

I had made a previous branch, which was getting 7 iters a second with a 3090 using 512x512, now however i get 1.5 iters a second, and I noticed that everything has been abstracted. I used default settings. 

Is there a reason for the significant slowdown?

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
Which branch is that? There were changes to optimization routines on `dev` recently and some folk experienced a slowdown. You can read about it in #957

**Comment by sathiathirumal** [comment]
I am seeing this in the master branch as of today. My original clone was on Sep10, and it was running very fast (6 it/s) on my 3080Ti. With a git pull today,  it is down to 1.75 it/s! What is the issue here?

**Comment by ZeroCool940711** [comment]
@sathiathirumal check that the default options dont have optimized or other similar options enabled by default, that might be slowing it down.

**Comment by sathiathirumal** [comment]
@ZeroCool940711 turns out the latest Nvidia drivers from today (Gameready drivers 517.48) solved this problem - I now hit upto 10.78 it/s !!!

**Comment by ZeroCool940711** [comment]
@sathiathirumal glad to know it got fixed.
