### ISSUE TITLE
[Bug]: Textual Inversion not working

### ISSUE THREAD

**Issue by VikingUnleashed** [sd-webui/stable-diffusion-webui#1065]
### What happened?

Don't know if I'm doing something wrong or if it's a bug. When running a prompt in the WebUI (no hardware acceleration, chromium browser) I get an error trying to use a textual_inversion embedding, with learned_embeds.bin dropped into the "embeddings file for textual inversion" box.  ex "in the style of *" 
![image](https://user-images.githubusercontent.com/113392586/189764761-8505d06d-a330-44da-a48e-debd654f9c39.png)

Attempted with both my own training and one downloaded from https://huggingface.co/sd-concepts-library and received similar errors

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\NoMassesForThePity\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\NoMassesForThePity\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\NoMassesForThePity\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\NoMassesForThePity\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\NoMassesForThePity\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\NoMassesForThePity\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 949, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 670, in process_images
    load_embeddings(fp)
  File "scripts/webui.py", line 359, in load_embeddings
    model.embedding_manager.load(fp.name)
  File "c:\stable_diffusion\stable-diffusion-main\ldm\modules\embedding_manager.py", line 138, in load
    self.string_to_token_dict = ckpt["string_to_token"]
KeyError: 'string_to_token'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Qualzz** [comment]
You should use a .pt file if I remember correctly.

**Comment by DrakenZA** [comment]
> You should use a .pt file if I remember correctly.

The most common type of embedding are the .bins getting generated by diffuser.

This code should support that, instead of this random .pt from some random notebook.

**Comment by Qualzz** [comment]
> 

Probably, i'm just giving the answer he need to make it works as explained in the documentation, not how things should be in theory. :D

**Comment by artsangel** [comment]
My apologies as I'm very new at Pytorch / Stable Diffusion. I'm sure there is a better way of doing this but it seems to work for me.

The file you want to change is ldm/modules/embedding_manager.py in the function load(self, ckpt_path)

`    def load(self, ckpt_path):
        ckpt = torch.load(ckpt_path, map_location='cpu')

        if isinstance(ckpt, nn.ParameterDict):
            self.string_to_token_dict = ckpt["string_to_token"]
            self.string_to_param_dict = ckpt["string_to_param"]
        else:
            file_token = list(ckpt.keys())[0]
            new_token = '*'

            tensor_size = ckpt[file_token].count_nonzero()
            newt = ckpt[file_token].reshape(1, tensor_size)
            newt = newt.half()

            nparam = nn.Parameter(data = newt, requires_grad=True)
            
            self.string_to_token_dict = {new_token: torch.tensor(265)}
            self.string_to_param_dict = nn.ParameterDict({new_token: nparam})   `

Then use * instead of your original trained token inside your prompt, ie "A teapot, painted by *"
