### ISSUE TITLE
[Bug]: Concurrent image generation via batching not working

### ISSUE THREAD

**Issue by JigenD** [sd-webui/stable-diffusion-webui#1083]
### What happened?

Selecting a higher batch count does not create images concurrently nor does it utilize higher amounts of VRAM. Instead it is creating images sequentially and hiding it under a single progress bar.

tested on: dev branch, txt2img

Not sure when this bug started as I was running a weeks old version of master prior.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JigenD** [comment]
Looks like this bug was introduced at [this commit](https://github.com/sd-webui/stable-diffusion-webui/commit/c459bfaacc6da98937e2e658b960780c0171383f), reverting the changes to attention.py fixes the issue, but reading up on this, it seems like this 'fix' also helped some performance issues for others.

I think batching is pretty important myself and use it frequently.

**Comment by codedealer** [comment]
@JigenD we have #974, can you check it out and see if it works with batching?

**Comment by JigenD** [comment]
@codedealer I checked out that PR and it does also appear to resolve the batching issue.

**Comment by JigenD** [comment]
I just pulled dev and confirmed that this issue is resolved.
