### ISSUE TITLE
[Bug]: Image stays above gallery and cannot be removed

### ISSUE THREAD

**Issue by i2chris** [sd-webui/stable-diffusion-webui#1091]
### What happened?

About 3 times today, there has been a glitch where the image in the gallery has stayed above the gallery icons and it cannot be removed, even after when generating a new image. I have to refresh the page.  I can't recreate it.
![Screenshot from 2022-09-13 19-03-53](https://user-images.githubusercontent.com/35810281/189978155-503c3834-8db2-463e-9d5f-d5dd56d4f0df.png)

I'm using the latest version

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
You're opening an issue in the wrong project.
