### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'k_diffusion'

### ISSUE THREAD

**Issue by vfyang** [sd-webui/stable-diffusion-webui#1103]
### What happened?

After installing for WebUI for Linux, I got this error:

Traceback (most recent call last):
  File "scripts/webui.py", line 57, in <module>
    import k_diffusion as K
ModuleNotFoundError: No module named 'k_diffusion'

I have done this:
pip install git+https://github.com/crowsonkb/k-diffusion/

and there is a  src/k_diffusion/ folder in webUI folder.

I will hit this error from scripts/webui.py or scripts/relauncher.py.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Custom settings

```shell
Centos 7.5.
Have not be able to launch website yet.
```

### Relevant log output

```shell
After complete the Linux-sd.sh, 
=====
Do you wish to customize the launch arguments for Ultimate Stable Diffusion?(This will be where you select Optimized mode, auto open in browser, share to public, and more.)1) Yes
2) No
#? 2
Maintaining current launch arguments...Running linux-setup.sh...Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 57, in <module>
    import k_diffusion as K
ModuleNotFoundError: No module named 'k_diffusion'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 1
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 57, in <module>
    import k_diffusion as K
ModuleNotFoundError: No module named 'k_diffusion'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brianredbeard** [comment]
Try installing the library by hand (it's referenced in `environment.yaml`):

https://github.com/sd-webui/stable-diffusion-webui/blob/833a91047df999302f699637768741cecee9c37b/environment.yaml#L40

e.g.:
`pip install -e git+https://github.com/hlky/k-diffusion-sd#egg=k_diffusion `

**Comment by fichl** [comment]
same issue here on a environment called ldo.
in environment.yaml name: seems to revert to ldm after every restart of webui.cmd instead of keeping it ldo.

after editing environment.yaml name to ldo i can launch webui once...

**Comment by rezinghost** [comment]
`pip install k-diffusion`  can fix this problem
but then called back pynvml missing

**Comment by davidmtsnz** [comment]
Hi vfyang. I am having your problem right now, and I hope you fixed it somehow. Did you??? I edited the install .bat so it refers to https://github.com/crowsonkb/k-diffusion/ but in the run .bat it doesn't find the folder...

**Comment by Victor-Cooper** [comment]
> Hi @vfyang. I am having your problem right now, and I hope you fixed it somehow. Did you??? I edited the install .bat so it refers to https://github.com/crowsonkb/k-diffusion/ but in the run .bat it doesn't find the folder... EDIT: for someone reading this, i got it running. Right click on install_sdco.bat and edit. Change the default k diffusion line for: call pip install -e git+https://github.com/crowsonkb/k-diffusion#egg=k_diffusion . SAVE. Same method but for webui, line 22 where it says import k_diffusion.sampling, change the line for: import k_diffusion .SAVE. It should work :) EDIT 2: cat Steps: 20, Sampler: Euler ancestral, CFG scale: 7.5, Seed: 2326120232 Time taken: 487.31s FINALLYYYY 💯

Hi. Look like "https://github.com/hlky/k-diffusion-sd" is an invalid url. Do you mean we need to change the url to "https://github.com/crowsonkb/k-diffusion/" in the installation bat file? Thanks!

**Comment by ZeroCool940711** [comment]
> > Hi @vfyang. I am having your problem right now, and I hope you fixed it somehow. Did you??? I edited the install .bat so it refers to https://github.com/crowsonkb/k-diffusion/ but in the run .bat it doesn't find the folder... EDIT: for someone reading this, i got it running. Right click on install_sdco.bat and edit. Change the default k diffusion line for: call pip install -e git+https://github.com/crowsonkb/k-diffusion#egg=k_diffusion . SAVE. Same method but for webui, line 22 where it says import k_diffusion.sampling, change the line for: import k_diffusion .SAVE. It should work :) EDIT 2: cat Steps: 20, Sampler: Euler ancestral, CFG scale: 7.5, Seed: 2326120232 Time taken: 487.31s FINALLYYYY 💯
> 
> Hi. Look like "https://github.com/hlky/k-diffusion-sd" is an invalid url. Do you mean we need to change the url to "https://github.com/crowsonkb/k-diffusion/" in the installation bat file? Thanks!

hlky deleted or made private most of his repos so, we should probably change the url to something else, if the version on `https://github.com/crowsonkb/k-diffusion/` works I think i will just change it to use that one instead, @davidmtsnz, Can you confirm whether that one works properly or not?, if it does then I will just do a quick fix for that to make sure we can install and run the code properly.

**Comment by ZeroCool940711** [comment]
Ok, thats weird, I already fixed that some time ago, we are using already the version from `https://github.com/crowsonkb/k-diffusion#egg=k_diffusion` .-.

**Comment by Victor-Cooper** [comment]
> Ok, thats weird, I already fixed that some time ago, we are using already the version from `https://github.com/crowsonkb/k-diffusion#egg=k_diffusion` .-.

Does it work properly? Thanks

**Comment by ZeroCool940711** [comment]
> > Ok, thats weird, I already fixed that some time ago, we are using already the version from `https://github.com/crowsonkb/k-diffusion#egg=k_diffusion` .-.
> 
> Does it work properly? Thanks

It should, if you can test and let me know just to be sure i would appreciate it. Also, you can go to out [discord server ](https://discord.gg/ttM8Tm6wge)and just message me there if you need help with anything, Im usually online most of the time so just mention me and I will try to help however I can.

**Comment by hlky** [comment]
The fork of k-diffusion was required for a time last year when k-diffusion did not have the correct setup files and was not available on pypi. It is no longer required as k-diffusion can be installed correctly from the original repo or from pypi.

**Comment by Victor-Cooper** [comment]
> The fork of k-diffusion was required for a time last year when k-diffusion did not have the correct setup files and was not available on pypi. It is no longer required as k-diffusion can be installed correctly from the original repo or from pypi.

could you give the command to install it from pypi? Is it `pip install k-diffusion`? Thanks!

**Comment by davidmtsnz** [comment]
That's right @Victor-Cooper, you have to change the url in the .bat file, or just use pip install: pip install -e git+https://github.com/crowsonkb/k-diffusion#egg=k_diffusion  , @ZeroCool940711 it works, I am using since I wrote the comment and no error given. I am right now fighting with the correct prompts, with 4 to 6 mins for each image... But yeah, it's working.
