### ISSUE TITLE
[Bug]: webui-streamlit.cmd keep pulling the git.. so needed setting are been erased in configs\webui\webui_streamlit.yaml

### ISSUE THREAD

**Issue by dudumaroja** [sd-webui/stable-diffusion-webui#1105]
### What happened?

I have a gtx 1660 ti.. and NEED the --precision full --no-half and --optimize to see anything other then green squares..
but the webui-streamlit.cmd erases all the settings i need to make it run. 

my solution is to lunch streamlite webui by hand to avoid this..

we need a external config file that will not be updated everytime

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
no_half: True
    precision: "Full"
    optimized: False
    optimized_turbo: True
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZeroCool940711** [comment]
Create a `userconfig_streamlit.yaml` file on `config/webui` next to the `webui_streamlit.yaml` and place your settings there, the `webui_streamlit.yaml` is meant to be the defaults settings config file and the `userconfig_streamlit.yaml` is where the user settings should go.

**Comment by Kasiya13** [comment]
Its been taken care of btw, update is now a seperate cmd file.
