### ISSUE TITLE
[Bug]: Can only have one negative "prompt"/can't weight negative prompts.

### ISSUE THREAD

**Issue by jangofett890** [sd-webui/stable-diffusion-webui#1123]
Negative Prompts don't seem to work with custom weights properly, as the way custom weights was setup means each custom weight is a new prompt and compared against each other, instead of the user friendly solution of using brackets.
Given the prompt "girl running in the rain in a field with a rainbow :3.0 dslr, colorful, spring :2.0 ### malformed, disfigured, distorted :2.0 black and white :8.0"
The AI will consider the "malformed, disfigured, distorted" as a negative prompt, and the resulting humanoid looks much better than without it, however "black and white" will be considered as a positive prompt, increasing the chance the image is rendered in black and white instead of preventing this from happening. I've even tried adding another ### after the first negative prompt and no luck.
Prompt as written above:
![image](https://user-images.githubusercontent.com/2407092/190160528-0c841dbe-8b6f-4167-b07d-34210e0a4702.png)
Prompt with extra ###:
![image](https://user-images.githubusercontent.com/2407092/190160912-274bb0f5-c660-4ed7-9eac-e3a10227deeb.png)
Prompt without black and white:
![image](https://user-images.githubusercontent.com/2407092/190159976-d09bae0a-5cd4-461f-a70f-a3e44ad1c266.png)
Prompt with black and white in the first negative prompt:
![image](https://user-images.githubusercontent.com/2407092/190161278-035752cd-4ca8-4ed5-9189-4c6ae6970105.png)

Edit: ~~Seems adding a prompt after the first negative lets you place in another negative, and weight it, still really weird for it to be this way, and makes writing prompts way harder:~~
![image](https://user-images.githubusercontent.com/2407092/190163176-4583c7ae-76ce-4574-b77c-3b4291828910.png)

~~Would like it if you don't have to go back in forth between positive and negative prompts and the ### is just a complete separator between negative and positive, having to flip flop between negative and positive is NOT intuitive at all...~~

Edit 2:
Welp, it's actually just bugged, because uping the weight of black and white made it black and white even though it should be considered negative: 
![image](https://user-images.githubusercontent.com/2407092/190166003-17699d5e-98e7-483f-9ee2-de7a2e5246d5.png)

_Originally posted by @jangofett890 in https://github.com/sd-webui/stable-diffusion-webui/issues/1035#issuecomment-1246697355_

**Comment by domportera** [comment]
I just tested this, my results say this is a consequence of having **Normalize Prompt Weights** enabled. Try it with that unchecked
