### ISSUE TITLE
[Bug]: Linux installer not working properly when using a different model file. (wd-v1-2-full-ema or sd-v1-4-full-ema)

### ISSUE THREAD

**Issue by BrahRah** [sd-webui/stable-diffusion-webui#1145]
### What happened?

The linux installer (linux-sd.sh) doesn't accept other model files (wd-v1-2-full-ema or sd-v1-4-full-ema) and broke up the installation process.

I had to open the installer and saw that I could just manually rename one of them and place it "models/ldm/stable-diffusion-v1/model.ckpt". However once I used ./linux-sd.sh I was asked if I wanted to update yes or no. I sadly went with yes and now it seems the installer installed everything in base environment instead of lsd....

I also get the *NVIDIA GeForce RTX 3060 with CUDA capability sm_86* error (see log) 
I'm guessing the installer installed the wrong pytorch/cuda version.

After that it's stuck in an infinite relaunching loop.

How do I revert what the installer did?

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Linux

### Relevant log output

```shell
https://pastebin.com/9hxnMXh7 (There was an error creating your issue: body is too long (maximum is 65536 characters).)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JoshuaKimsey** [comment]
Yes, my script is not built to handle other model files yet, as I was waiting to see if the UI would handle this instead. Currently, the Streamlit side is being made to handle this. In the near term, just name your model file to `sd-v1-4.ckpt`, delete the repo folder it cloned, and rerun the program again. That should fix it and get it up and running.
