### ISSUE TITLE
[Bug]: Could not find conda environment: ldm

### ISSUE THREAD

**Issue by Timkeeper2018** [sd-webui/stable-diffusion-webui#1151]
### What happened?

A bug happened! On windows, I installed anaconda and cleared all virtual environments, but the following error still appeared when running webui.cmd
`
E:\havefun\stable-diffusion-webui>webui.cmd
Environment name is set as ldm as per environment.yaml
anaconda3/miniconda3 detected in C:\ProgramData\anaconda3
Could not find conda environment: ldm
You can list all discoverable environments with `conda info --envs`.
`
Someone mentioned this error before but the workaround doesn't work anymore

It might be a bug that I didn't enter the base environment.
`
Traceback (most recent call last):
  File "E:\havefun\stable-diffusion-webui\scripts\webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
`

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
Looks like `conda env create` got lost in during the refactor of cmd files.
Launch `update_to_latest.cmd` instead see if it fixes it.

**Comment by redkjuegos** [comment]
> Looks like `conda env create` got lost in during the refactor of cmd files. Launch `update_to_latest.cmd` instead see if it fixes it.

apparently some other stuff is missing too,  check [This other Issue](https://github.com/sd-webui/stable-diffusion-webui/issues/1161)    It all seems to be connected

**Comment by johnsith22** [comment]
this did not work

**Comment by johnsith22** [comment]
still gives the error that 
![Uploading Screenshot_11.png…]()

**Comment by char-cole** [comment]
Not sure why this was closed, but it was still the first result on DDG for me.

I ran `conda env create` to see if that would fix the problem. It gave another issue: `environment.yml not found`. Well, `environment.yaml` exists, so I copied the contents into a new file `environment.yml` and ran the command again. Seems to be working ,it's been setting up for 10min and still going.
