### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ikesaber** [sd-webui/stable-diffusion-webui#1166]
### What happened?

Ubuntu 22.04.1 LTS

I ran into this error during [step 8](https://github.com/sd-webui/stable-diffusion-webui/wiki/Linux-Automated-Setup-Guide) of the installation process. I'm not sure how to resolve it. Please let me know if this is a known error or how I can correct it.

```
Do you wish to customize the launch arguments for Ultimate Stable Diffusion?(This will be where you select Optimized mode, auto open in browser, share to public, and more.)1) Yes
2) No
#? 2
Maintaining current launch arguments...Running linux-setup.sh...Could not find conda environment: lsd
You can list all discoverable environments with `conda info --envs`.

Relauncher: Launching...
Traceback (most recent call last):
  File "/home/user/Downloads/StableDiffusion/stable-diffusion-webui/scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 1
Relauncher: Launching...

# This repeated until I cancelled the script

^CTraceback (most recent call last):
  File "/home/user/Downloads/StableDiffusion/stable-diffusion-webui/scripts/relauncher.py", line 64, in <module>
    time.sleep(1)
KeyboardInterrupt

```

### Version

0.0.1 (Default)

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nabushika** [comment]
Can you try running `conda create -f environment.yaml` and then run the script again? Thanks

**Comment by Hadmos** [comment]
> Can you try running `conda env create -f environment.yaml` and then run the script again? Thanks

I have the same issue and I tried that. It said `CondaValueError: prefix already exists: C:\Users\hadmos\miniconda3\envs\ldm`. The issue is still there after relaunch.

**Comment by ikesaber** [comment]
I came back to stable diffusion recently and `./linux-sd.sh` worked for me this time with no changes... I don't know if something was done to cause this issue to be resolved but wanted to provide an update.
