### ISSUE TITLE
[Bug]: Runtime Error

### ISSUE THREAD

**Issue by SingingTurnip** [sd-webui/stable-diffusion-webui#1167]
### What happened?

When trying to use **Stable Diffusion Image-to-Image Unified** I get the following error:

`RuntimeError: The size of tensor a (133) must match the size of tensor b (136) at non-singleton dimension 3`

I am using Stable Diffusion Web UI Altryne on my Google colab(free).

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Where are you running the webui?

Colab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yumenoru** [comment]
The selected area in the editor must correspond to the aspect ratio in pixels of the generated image. That is, if you are generating a 512x512 image, then the selected area must match the aspect ratio of 1:1.
In your case "tensor a (133) must match the size of tensor b (136)" means that you must either make the selection in editor slightly wider or slightly shorter in height.
