### ISSUE TITLE
[Bug]: No module named 'streamlit_nested_layout'

### ISSUE THREAD

**Issue by RaymondTracer** [sd-webui/stable-diffusion-webui#1170]
### What happened?

The WebUI won't work correctly on the dev branch.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Relevant log output

```shell
2022-09-16 10:46:29.123 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\user\Documents\GitHub\stable-diffusion-webui\scripts\webui_streamlit.py", line 5, in <module>
    import streamlit_nested_layout
ModuleNotFoundError: No module named 'streamlit_nested_layout'
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Kasiya13** [comment]
That one currently isn't being used, you can delete the import line from the webui_streamlit.py and the environment.yaml, it should work afterwards

**Comment by ZeroCool940711** [comment]
That import IS being used, you only need to import it for it to allow nested layouts, without it, you can expect to get a lot more errors soon. The solution is NOT to delete the import but instead install the dependency which should be installed anyway if you are using the cmd or updating your environment from the `environment.yaml` file frequently.
