### ISSUE TITLE
[Bug]: Could not find conda environment: ldm

### ISSUE THREAD

**Issue by unsellingwizard** [sd-webui/stable-diffusion-webui#1172]
### What happened?

When trying to start webui-streamlit.cmd I got the error `Could not find conda environment: ldm`. 
I managed to solve the problem by creating the custom-conda-path.txt file and adding C:\Users\rkrap\miniconda3 to it.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Environment name is set as ldm as per environment.yaml
anaconda3/miniconda3 detected in C:\ProgramData\miniconda3
Could not find conda environment: ldm
You can list all discoverable environments with `conda info --envs`.

C:\Program Files\Python310\python.exe: No module named streamlit

[process exited with code 1 (0x00000001)]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by graniton** [comment]
I am having the same problem using  Windows 10.  Upon running webui.cmd, I get the message 

> Could not find conda environment: ldm

I then get further messages:

> No module named 'cv2'

followed by infinite relaunches with the same results
