### ISSUE TITLE
[Bug]: Image-to-image unified crash

### ISSUE THREAD

**Issue by mikrkilk** [sd-webui/stable-diffusion-webui#1193]
### What happened?

Firstly, I create an image in text2img tab, push it to img2img tab and create some results. This works fine. Afterwards, I return to the text2img tab to create a new image with a new prompt. When I then push a new result in the img2img tab, there are some results and settings from the previous run still visible. I enter a new prompt for the new image and try to generate new results, but I'm met with a message "generation finished" instantly. In my command prompt I can see an error message
![image](https://user-images.githubusercontent.com/25008156/190857513-b1c4d83b-6d71-431e-8066-2fa6beae545d.png)

I've been able to trigger this error for several times. It seems to happen only when I'm doing a new img2img generation with some of the previous results still visible.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0dr** [comment]
This can be temporarely fixed by opening the "Advanced editor" ans saving without any changes.
