### ISSUE TITLE
[Bug]: what wrong，it Stuck in an endless loop

### ISSUE THREAD

**Issue by neutronslime** [sd-webui/stable-diffusion-webui#1207]
### What happened?

I followed the tutorial for windows，but it still can't work 

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Where are you running the webui?

Windows

### Relevant log output

```shell
Pip subprocess error:
ERROR: Command errored out with exit status 128: git fetch -q --tags Check the logs for full command output.

failed

CondaEnvException: Pip failed

Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
        Relaunch count: 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonatanhedborg** [comment]
I also started getting this after pulling latest from master

**Comment by sedetweiler** [comment]
Same.  Stuck on several modules now.

Traceback (most recent call last):
  File "scripts/webui.py", line 122, in <module>
    from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker
ModuleNotFoundError: No module named 'diffusers'
Relauncher: Process is ending. Relaunching in 1s...
        Relaunch count: 1
Relauncher: Launching...

**Comment by Hadmos** [comment]
also have the same issue.

**Comment by BellemareMederic** [comment]
Me to im stuck on Installing pip dependencies: and the process not using I/O or Network at all :\

**Comment by mykeehu** [comment]
I found a temporary solution!
1. close the cmd window where pip dependencies stopped
2. open a new cmd in the program directory
3. type: conda activate ldm
4. once you have entered the enviroment, type: pip install -r (name of condaenv.*.requirements.txt left in the folder by the previous cmd, e.g. condaenv.be22qg2b.requirements.txt )
5. at one point the installation stops (this is what caused the problem!), waits for a response (igonre, wipe), I chose ignore here.
6. run the installer and you are done!

**Comment by BellemareMederic** [comment]
dont have any condaenv file with requirement in it

**Comment by rhit-perryca** [comment]
I dont see the requirements text file in the current dir after I open up the conda environment. Am I looking in the wrong place?

**Comment by mykeehu** [comment]
> I dont see the requirements text file in the current dir after I open up the conda environment. Am I looking in the wrong place?

There the environment.yaml file and webui.cmd creates the enviroment

**Comment by mykeehu** [comment]
Run the webui.cmd file, it will start the enviroment update and stop at a point. the TXT file will be created in the Background. You close the prompt and the TXT stays there.

**Comment by coffeegremlin** [comment]
I also had some issues and realized I forgot to run `conda activate` then run `conda init zsh` since I'm using ZSH currently. Conda also supports bash, fish, tcsh, zonsh, and powershell.
