### ISSUE TITLE
Add toggle to use timestamp in filename instead of prompt when 'sort samples by prompt' toggle is enabled (Use timestamp for folder names instead of prompt.)

### ISSUE THREAD

**Issue by ZeroCool940711** [sd-webui/stable-diffusion-webui#121]
I think it would be better to use a timestamp of when the image or prompts were generated for the folder names instead of the prompt itself, not only you need to sanitize the prompt so it doesn't have any invalid character but on Windows it's really easy to have paths too long, I recently ran into this problem, the path where I had Stable Diffusion WebUI was something like `D:\ZeroCool940711\Projects\Python\Machine Learning\Image Generation\stable-diffusion` so when trying to access one of the generations I made previously which was on the folder `D:\ZeroCool940711\Projects\Python\Machine Learning\Image Generation\stable-diffusion\outputs\txt2img-samples\samples\an_adventurer_crossing_a_river_in_a_boat_finds_an_abandoned_giant_skull_in_a_dark_cave_with_many_plants_around_it_while_its_raining` I could neither open the images nor the yaml files in there because the path was too long, any other folder that was shorter like `A_lake_in_the_mountains` was accessible but not those with long folder names, by using timestamps you would always get a folder name like `2022-08-27_23-36-49` which would be shorter and have almost always a fixed size, it will also make it easier to find the latest generation as it will always be the latest one.

**Comment by HenkDz** [comment]
Actually I like having the prompt in folder name

**Comment by RecursiveHook** [comment]
> Actually I like having the prompt in folder name

That's why an option to use either prompt or timestamp would be appreciated. 

Other folks also like being able to access their files on a Windows machine. :wink:
