### ISSUE TITLE
[Bug]: Aspect Ratio for Mask replacement always returns 1:1

### ISSUE THREAD

**Issue by sedetweiler** [sd-webui/stable-diffusion-webui#1213]
### What happened?

Use the tiny brush to mask an area and do a replacement on the masked area.  This squishes the output into a square destroying the aspect ratio.  This also means that using the result in photoshop is impossible since the entire thing is squished.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0dr** [comment]
Can confirm, using img2img in mask mode with an image that is not of ratio 1.0, the actual applied mask does not match the one in the preview. (scaled and moved relative to the upper left corner)

Windows
Webui
dev [e2d6e220230d8dc0e850b57f814d49976a541d38]

**Comment by MasterZap** [comment]
Yes and paintint the mask at any time the image is not in 1:1 scale is super-wonky, allowing you to paint outside the window and it almost seeming like the masks aspect ratio gets applied twice, or something.... !?
