### ISSUE TITLE
[Bug]: App fails to launch due to StableDiffusionSafetyChecker

### ISSUE THREAD

**Issue by ransoing** [sd-webui/stable-diffusion-webui#1231]
### What happened?

Upon attempting to launch, I get this error:

```
File "scripts/webui.py", line 122, in <module>
    from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker
ModuleNotFoundError: No module named 'diffusers'
```

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
Not a bug. You didn't install correctly.

**Comment by flowerdealer** [comment]
I had a working installation, updated the repository, reran and also started getting this error.

**Comment by ransoing** [comment]
@flowerdealer that was my situation as well. The latest update breaks existing installations. Re-cloning and following the install instructions eliminates the error.

**Comment by flowerdealer** [comment]
Yeah I also reinstalled and it works now.
