### ISSUE TITLE
File not found error when using Euler A with long prompts

### ISSUE THREAD

**Issue by ange321** [sd-webui/stable-diffusion-webui#1237]
### What happened?

Current  environment.yaml hash: 148c41826b9b55a6387ca46625329da99cb75dc8

On the Gradio UI, if a long prompt is used on txt2img in conjunction with "Euler A" sampling, the second time an image is generated, the following error occurs:

  File "scripts/webui.py", line 1408, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 1271, in process_images
    save_sample(image, sample_path_i, filename, jpg_sample, write_info_files, write_sample_info_to_log_file, prompt_matrix, init_img, uses_loopback, uses_random_seed_loopback, skip_save,
  File "scripts/webui.py", line 700, in save_sample
    with open(f"{filename_i}.yaml", "w", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/txt2img-samples\\samples\\a_photograph_of_extra-terrestrial_life,_alien_lifeforms,_chimera,_hybrid,_ultra_realistic,_depth_of_field,_sharp_focus,_smooth,_\\00000-20_k_euler_a_1120591182_0.00.yaml'

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
To be reaching path limit you must have the root folder of the repo a longer path than for example `C:/Users/user/Documents/GitHub/stable-diffusion-webui/`

Move it somewhere else.

**Comment by DiBianoR** [comment]
I don't think you can move it after installation.
