### ISSUE TITLE
[Bug]: Linux server script didn't create conda environnement right

### ISSUE THREAD

**Issue by tr1p0p** [sd-webui/stable-diffusion-webui#1254]
### What happened?

After a update of the git with the linux-script of the official guide, a LOTS of pip modules are missing and the webui cannot start with error of modules missing in loop. In my case "frontend" module.

Running this on Debian 11

If you use pip into the conda env to install the module it's a never ending game : to be clear : the envrionnement installation DON'T install modules and pip.

It seem 75% of issues are for windows users, so every issues that talk about that just talk about webui.cmd and all. I just look for a pip command that just... install modules correctly, it's hidden on here because ALL pass with environnement.yaml and all.

### Version

0.0.1 (Default)

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
The linux installation script is going to be removed. It's useless. Anyone using linux shouldn't need it. If you do need an installation script, you should be using windows.

**Comment by tr1p0p** [comment]
> The linux installation script is going to be removed. It's useless because anyone using linux shouldn't need it. If you do need an installation script, you should be using windows.

Wait, what ?

Our ALL installation guide is only around this one script, so you gonna deleted and all way of installing stable-diffusion and leave it only to windows users ?

And, if you read my git issue you will see i don't NEED a script (remember ; OUR guide only give this options) i actually just need a... pip command and a good guide that actually SHOW the steps to do to launch webui ?

So, yeah could be more precise : can you do a proper linux guide ? Not a one that revolve around script that you will delete and tell to user that they should go windows ?

What a joke, really.
