### ISSUE TITLE
[Bug]: docs/1.linux-installation.html 404 Not Found

### ISSUE THREAD

**Issue by brodia10** [sd-webui/stable-diffusion-webui#1275]
### What happened?

It looks like the Linux Installation Wiki was revised yesterday and marked as deprecated. 

I am referring to this link here:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/29584063/191862562-c0783034-1635-4f45-829a-ab9a584c4fe9.png">

It says to refer to the new documentation which when visited returns a 404. 

https://sd-webui.github.io/stable-diffusion-webui/docs/1.linux-installation.html

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/29584063/191862137-0c4d8011-4be2-4f8b-9e2e-7d3ca43c4ef0.png">

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
Linux guide lives here now https://sd-webui.github.io/stable-diffusion-webui/docs/2.linux-installation.html

I'll change the link

**Comment by octoshrimpy** [comment]
> Linux guide lives here now https://sd-webui.github.io/stable-diffusion-webui/docs/2.linux-installation.html
> 
> I'll change the link

this link is not working either, I get a 404

**Comment by ZeroCool940711** [comment]
@octoshrimpy we recently changed the name of the repo and organization, we are still updating things, the docs can be found here
https://sygil-dev.github.io/sygil-webui/docs/2.linux-installation.html

**Comment by zhafed** [comment]
here the new link:

[https://sygil-dev.github.io/sygil-webui/docs/Installation/linux-installation](https://sygil-dev.github.io/sygil-webui/docs/Installation/linux-installation)
