### ISSUE TITLE
[Bug]: Sometimes "failed to fetch"

### ISSUE THREAD

**Issue by jcplus** [sd-webui/stable-diffusion-webui#1277]
### What happened?

Everytime now I started a new colab and run generating on browsers, the first run is normally ok. Then the jobs after  will not display any images. No parameters changed. No matter how simple or how complex the prompts are.
In browser console, the error is always:
```
Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR
224487.gradio.app/:1 Uncaught (in promise) TypeError: Failed to fetch
```

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Where are you running the webui?

Colab

### Custom settings

```shell
None
```

### Relevant log output

```shell
All jobs finished as `[MemMon] Stopped recording.`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by licoriceleaf** [comment]
Getting this too, still not resolved.

**Comment by jcplus** [comment]
Temporary solution is only use the ui but view results in Google drive.
Sometimes after long waiting, you may need to refresh the page otherwise the ui doesn't send any new requests even you pushed the button.
