### ISSUE TITLE
[Bug]: Textual Inversion not working properly in Streamlit

### ISSUE THREAD

**Issue by localhost-server** [sd-webui/stable-diffusion-webui#1295]
### What happened?

Whenever I switch my page to textual inversion from stable diffusion section I get blank output in front.
![Screenshot_20220924_173113](https://user-images.githubusercontent.com/99524394/192096882-2f71e847-413f-44b2-ad4b-9d9807d2c70c.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZeroCool940711** [comment]
That page is not implemented yet, it is empty for now.

**Comment by localhost-server** [comment]
ok got it
