### ISSUE TITLE
[Bug]: SD Textual inversion support

### ISSUE THREAD

**Issue by ARDEACT** [sd-webui/stable-diffusion-webui#1318]
### What happened?

It's been a month since the last commit to SD Textual inversion, a really powerful technique that's not being supported. The latest version of SD-Webui does not support textual inversion as it does not show up anymore. Please update.

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lzardy** [comment]
You can run textual inversion using this script https://github.com/sd-webui/stable-diffusion-webui/blob/master/scripts/diffusers_textual_inversion_2.py

**Comment by ARDEACT** [comment]
> You can run textual inversion using this script https://github.com/sd-webui/stable-diffusion-webui/blob/master/scripts/diffusers_textual_inversion_2.py

I see Textual inversion is implemented into Streamlit, although I get a blank page.

**Comment by lzardy** [comment]
Although there is not a disclosure, the feature is WIP.

**Comment by ARDEACT** [comment]
> Although there is not a disclosure, the feature is WIP.
Is this command line only?

**Comment by ARDEACT** [comment]
It seems that file is for textual inversion training, not inferencing.

**Comment by lzardy** [comment]
Alright, so you want to use concepts trained using textual inversion. This should be present in the project via the Concept Library. If you have concepts in the library, you can use them with `<concept>`, replacing "concept" with the appropriate name.

**Comment by ARDEACT** [comment]
Ok the implementation of "concepts" is much more convenient. But the training for colab requires a Hugging face token to automatically upload, which is not desired. Is there any way around this so I can train and keep my own embeds?

**Comment by ZeroCool940711** [comment]
@ARDEACT we have cloned the huggingface concepts library and we keep it on a repository on our organization, it's updated regularly, you can find it [here](https://github.com/sd-webui/sd-concepts-library/), that same link is shown if you visit the concepts library tab on our WebUI.

**Comment by ARDEACT** [comment]
> @ARDEACT we have cloned the huggingface concepts library and we keep it on a repository on our organization, it's updated regularly, you can find it [here](https://github.com/sd-webui/sd-concepts-library/), that same link is shown if you visit the concepts library tab on our WebUI, you can just download it from that link or clone it into the `models/custom` folder so they have a folder structure like `models/custom/sd-concepts-library/concept_name`, once you have it there the concepts will show on the Concepts Library tab on the UI, your custom concepts can also be placed there but be careful to use the same folder structure as other concepts.

Can I train my own concepts via colab without requiring a Hugging face token?

**Comment by ARDEACT** [comment]
> @ARDEACT we have cloned the huggingface concepts library and we keep it on a repository on our organization, it's updated regularly, you can find it [here](https://github.com/sd-webui/sd-concepts-library/), that same link is shown if you visit the concepts library tab on our WebUI, you can just download it from that link or clone it into the `models/custom` folder so they have a folder structure like `models/custom/sd-concepts-library/concept_name`, once you have it there the concepts will show on the Concepts Library tab on the UI, your custom concepts can also be placed there but be careful to use the same folder structure as other concepts.

Ok so training on Colab takes for me 4 hours which isn't possible because of Colab limitations. Can I resume training when I lose connection?

**Comment by ARDEACT** [comment]
> @ARDEACT we have cloned the huggingface concepts library and we keep it on a repository on our organization, it's updated regularly, you can find it [here](https://github.com/sd-webui/sd-concepts-library/), that same link is shown if you visit the concepts library tab on our WebUI, you can just download it from that link or clone it into the `models/custom` folder so they have a folder structure like `models/custom/sd-concepts-library/concept_name`, once you have it there the concepts will show on the Concepts Library tab on the UI, your custom concepts can also be placed there but be careful to use the same folder structure as other concepts.

I also tried putting a concept into the /models/custom/sd-concepts-library/<concept_name> but it doesn't show up in the stream lit UI.

**Comment by lzardy** [comment]
> > @ARDEACT we have cloned the huggingface concepts library and we keep it on a repository on our organization, it's updated regularly, you can find it [here](https://github.com/sd-webui/sd-concepts-library/), that same link is shown if you visit the concepts library tab on our WebUI, you can just download it from that link or clone it into the `models/custom` folder so they have a folder structure like `models/custom/sd-concepts-library/concept_name`, once you have it there the concepts will show on the Concepts Library tab on the UI, your custom concepts can also be placed there but be careful to use the same folder structure as other concepts.
> 
> I also tried putting a concept into the /models/custom/sd-concepts-library/<concept_name> but it doesn't show up in the stream lit UI.

It requires a `concept_images` folder, a `learned_embeds.bin` file, and the `type_of_concept.txt`

**Comment by ARDEACT** [comment]
> > > @ARDEACT we have cloned the huggingface concepts library and we keep it on a repository on our organization, it's updated regularly, you can find it [here](https://github.com/sd-webui/sd-concepts-library/), that same link is shown if you visit the concepts library tab on our WebUI, you can just download it from that link or clone it into the `models/custom` folder so they have a folder structure like `models/custom/sd-concepts-library/concept_name`, once you have it there the concepts will show on the Concepts Library tab on the UI, your custom concepts can also be placed there but be careful to use the same folder structure as other concepts.
> > 
> > 
> > I also tried putting a concept into the /models/custom/sd-concepts-library/<concept_name> but it doesn't show up in the stream lit UI.
> 
> It requires a `concept_images` folder, a `learned_embeds.bin` file, and the `type_of_concept.txt`

Still 0 results. I cloned the repo and started over, still nothing.

**Comment by lzardy** [comment]
> > > > @ARDEACT we have cloned the huggingface concepts library and we keep it on a repository on our organization, it's updated regularly, you can find it [here](https://github.com/sd-webui/sd-concepts-library/), that same link is shown if you visit the concepts library tab on our WebUI, you can just download it from that link or clone it into the `models/custom` folder so they have a folder structure like `models/custom/sd-concepts-library/concept_name`, once you have it there the concepts will show on the Concepts Library tab on the UI, your custom concepts can also be placed there but be careful to use the same folder structure as other concepts.
> > > 
> > > 
> > > I also tried putting a concept into the /models/custom/sd-concepts-library/<concept_name> but it doesn't show up in the stream lit UI.
> > 
> > 
> > It requires a `concept_images` folder, a `learned_embeds.bin` file, and the `type_of_concept.txt`
> 
> Still 0 results. I cloned the repo and started over, still nothing. ![image](https://user-images.githubusercontent.com/46211295/192188816-107db904-72c1-4155-840a-27544b1ffe78.png)

None of those have a concept_images folder. They are known to not show.

**Comment by ARDEACT** [comment]
They all have a concept_images folder that contain images.

**Comment by lzardy** [comment]
> They all have a concept_images folder that contain images.

Have you tried dev branch?

**Comment by ARDEACT** [comment]
There's no dev branch

**Comment by ARDEACT** [comment]
Solution: Cleared Cache on Steamlit

**Comment by lzardy** [comment]
> 

`git clone https://github.com/sd-webui/stable-diffusion-webui`
`git checkout dev`

**Comment by ARDEACT** [comment]
Ok but I still need to find a way to train on Colab without having to babysit it for 4 hours to make sure it doesn't close runtime. And the fact that the providing colab doesn't even have checkpoints or a continuation of training is troubling.

**Comment by lzardy** [comment]
> 

The colab is not actively maintained by this team.

**Comment by ARDEACT** [comment]
Is there a repo or documentation on training locally?

**Comment by ZeroCool940711** [comment]
@ARDEACT you should join our [discord server](https://discord.gg/mYZwzqhU4j), we are always there and we also have a pretty active community on discord that can also help you with it, you will get help faster than here on GitHub and it will spam less our emails with so many messages back and forth, both yours and ours :)
