### ISSUE TITLE
[Bug]: Streamlit UI contains tracking script enabled by default

### ISSUE THREAD

**Issue by poshul** [sd-webui/stable-diffusion-webui#1378]
### What happened?

The Streamlit UI contains calls to an analytics script on segment.com. There is no opt-in or notification banner, so this is probably a violation of the great mess known as the GDPR. 

Suggested solution:
Disable analytics by default, or have a prompt on first launch (like the Streamlit email prompt) to get affirmative consent from the user. NB: I am not a lawyer and this is not legal advice.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
It is **disabled** by default...
