### ISSUE TITLE
[Bug]: hlky RunPod template doesnt work with the RunPod Proxy

### ISSUE THREAD

**Issue by githubartman** [sd-webui/stable-diffusion-webui#1391]
### What happened?

When running the official latest hlky RunPod template I ran into problems on RunPod. In the standard configuration the "Connect to HTTP Button" doesnt even show up.

After contacting RunPod support it was suggested to add "8501" as an exposed HTTP port to make it work. When connecting to the RunPod proxy the streamlit app shows that it is loading, but nothing happens afterwards

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
![image](https://user-images.githubusercontent.com/106811348/193471212-10a97c0c-c990-48b2-b5ff-3b5e156a4e8d.png)

Use the public ip and external port for internal port 8501

It is exposed as tcp port for a reason.

Runpod's http proxy does not appear to support websocket which is used by streamlit

**Comment by githubartman** [comment]
Thanks, it worked.

The problem was that any other RunPod that is not from the Secure Cloud does not support your / Streamlits configuration. So I had to choose a GPU from the Secure Cloud to make it work.

**Comment by hlky** [comment]
> Thanks, it worked.
> 
> The problem was that any other RunPod that is not from the Secure Cloud does not support your / Streamlits configuration. So I had to choose a GPU from the Secure Cloud to make it work.

I've used community cloud pods, it's just that not all of them support TCP ports
