### ISSUE TITLE
[Info][Bug]: Now this is like malware %)

### ISSUE THREAD

**Issue by x-name** [sd-webui/stable-diffusion-webui#1400]
Looks like malware in new version. Why you connect a your cluster by default?
stablehorde.net
This is very bad practice.

!!! **use this github carefully** !!!

Now I don't know what more surprises will be here...

**Comment by hthetiot** [comment]
I think it's fixed by https://github.com/sd-webui/stable-diffusion-webui/pull/1393

**Comment by hlky** [comment]
A mistake was made merging the pull request that allows users to join the cluster. It was rectified very quickly.

Commenting on things you do not understand is very bad practice.
