### ISSUE TITLE
[Bug]: deleting z_version_env.tmp does not reinstall the dependencies

### ISSUE THREAD

**Issue by Michu44** [sd-webui/stable-diffusion-webui#1408]
### What happened?

the Webui_streamlit.cmd tells you that you can delete z_version_env.tmp to reinstall the dependencies when no update was performed via. git.

Now I had an issue where pip failed to install a dependency, and now I'm stuck in a loop when using the webui_streamlit.cmd, since it never reinstalls the dependencys.

Either there must be a new Prompt in the  webui_streamlit.cmd to reinstall all dependencys even if there are no updates which should then execute 

  call conda env create --name "%v_conda_env_name%" -f environment.yaml
  call conda env update --name "%v_conda_env_name%" -f environment.yaml 

or the script must accomondate the fact that z_version_env.tmp was deleted, even before fetching any git changes (probably, not quite sure yet).

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Michu44** [comment]
Found this because of https://github.com/sd-webui/stable-diffusion-webui/issues/1409

**Comment by loki2020** [comment]
This sounds like what I'm after as well. 1414. Kasiya13, how do you go about manual installs, i tried one with pip install opencv-python and is caused the error message I was getting from missing module cv2, after the install it said missing Gradio then I get scared and ran away. But ya, how do you manual install missing dependencies?? (I have no idea what I'm doing ;)

**Comment by MosJef0** [comment]
I was running into this problem as well, and it seems to trace back to having an outdated version of Microsoft Visual C++. After forcing the installation of all pip dependencies with Michu44's suggested code, I got the following errors:

> Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (PEP 517): started
  Building wheel for pycocotools (PEP 517): finished with status 'error'
Failed to build pycocotools

>Pip subprocess error:
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\jeffm\.conda\envs\ldm\python.exe' 'C:\Users\jeffm\.conda\envs\ldm\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\jeffm\AppData\Local\Temp\tmpdev6shgl'
       cwd: C:\Users\jeffm\AppData\Local\Temp\pip-install-lkyehjo2\pycocotools_3684cf55621b4e80a8b0f0cb30addb8d
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-38
  creating build\lib.win-amd64-cpython-38\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-cpython-38\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-38\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-cpython-38\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-38\pycocotools
  running build_ext
  cythoning pycocotools/_mask.pyx to pycocotools\_mask.c
  building 'pycocotools._mask' extension
  C:\Users\jeffm\AppData\Local\Temp\pip-build-env-0hl_0qfm\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\jeffm\AppData\Local\Temp\pip-install-lkyehjo2\pycocotools_3684cf55621b4e80a8b0f0cb30addb8d\pycocotools\_mask.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

>ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools which use PEP 517 and cannot be installed directly

>failed

>CondaEnvException: Pip failed

It seems like whatever PEP 517 is can only be installed manually through downloading [MS's build tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) . Once I updated that and ran the pip dependencies installation once via Michu44's suggested method, everything is working fine.

**Comment by MosJef0** [comment]
Errr, may have spoke too soon. Streamlit is loading, but I'm now getting the following errors in the command prompt after it loads:

> 2022-10-04 21:46:52.178 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\jeffm\.conda\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\jeffm\stable-diffusion-webui\scripts\webui_streamlit.py", line 174, in <module>
    layout()
  File "C:\Users\jeffm\stable-diffusion-webui\scripts\webui_streamlit.py", line 138, in layout
    layout()
  File "scripts\txt2img.py", line 314, in layout
    index=st.session_state["GFPGAN_models"].index(st.session_state['defaults'].general.GFPGAN_model))
ValueError: 'GFPGANv1.4' is not in list

And within the Streamlit UI I'm getting the following error:

> Missing Submit Button
This form has no submit button, which means that user interactions will never be sent to your Streamlit app.
To create a submit button, use the st.form_submit_button() function.
For more information, refer to the [documentation for forms](https://docs.streamlit.io/library/api-reference/control-flow/st.form).

So I'm not sure if more dependencies are still not being properly checked for?

**Comment by superwhyun** [comment]
> 
as a quick detour, 
download GFPGANv1.4 from [link](https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth), and put it to 'src/gfpgan/experiments/pretrained_models'

**Comment by MosJef0** [comment]
> > 
> 
> as a quick detour, download GFPGANv1.4 from [link](https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth), and put it to 'src/gfpgan/experiments/pretrained_models'

This fixed all of my issues, thanks! 🙏
