### ISSUE TITLE
[Bug]: Unable to run both GFPGAN and RealESRGAN in txt2img and img2img

### ISSUE THREAD

**Issue by DasWookie** [sd-webui/stable-diffusion-webui#1425]
### What happened?

When running either txt2img or an img2img and selecting to execute both face correction and upscale, only face correction fires. Upscale doesn't run. If you don't run face correction, then upscale works fine. Seems to be only when both are selected to be used. I'm running latest code on Master branch as of 10/2 AlmaLinux release 9.0 (Emerald Puma). This happens if you are running GFPGAN 1.3 or 1.4, and either RealESRGAN 4x or 4xAnime. Streamlit v1.13.0. I've verified all dependencies are at correct versions via pip install -r requirements.txt as well conda env update -f environment.yaml ... etc etc etc. Everything is there and at the right versions.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
Gradio or Streamlit?

Try dev, if you're using Streamlit there have been some fixes to gfpgan and esrgan.

**Comment by jbuck2005** [comment]
I can confirm that this is happening with the latest updates, despite everything previously working fine.
To test the dev branch, I switched and it has had zero positive effect.
