### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by blackwing12344** [sd-webui/stable-diffusion-webui#1427]
### What happened?

so, I was trying to fix a previous issue where it would get stuck in a loop saying no module named "cv2" and relaunching
I followed [this](https://github.com/sd-webui/stable-diffusion-webui/issues/1207#issuecomment-1251272101) guide but it errored out and gave me this
![image](https://user-images.githubusercontent.com/77736883/193949549-5e51f173-087a-4e76-beed-04e78c9ba208.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parsec501** [comment]
You need to install the VS build tools so that it can compile the dependency. There is a url in the output, download it from there.

**Comment by blackwing12344** [comment]
> > You need to install the VS build tools so that it can compile the dependency. There is a url in the output, download it from there.
> 
> No. Wrong. This dependency was removed. If you do not know what you are on about keep quiet. Incorrect information does not help anyone.

Then what is going on?

**Comment by hlky** [comment]
@blackwing12344 There is no issue. The dependency was removed.
