### ISSUE TITLE
[Bug]: No module named open_clip

### ISSUE THREAD

**Issue by Silur** [sd-webui/stable-diffusion-webui#1430]
### What happened?

First run using docker-compose.amd.yml, with `GFPGANv1.4.pth` manually downloaded into `/src` as suggested in https://github.com/sd-webui/stable-diffusion-webui/issues/1408#issuecomment-1268494106

Results in the following (at startup and at every model inference):
```
File "/opt/conda/lib/python3.7/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
File "/sd/scripts/webui_streamlit.py", line 174, in <module>
    layout()
File "/sd/scripts/webui_streamlit.py", line 149, in layout
    from img2txt import layout
File "/sd/scripts/img2txt.py", line 47, in <module>
    import open_clip
ModuleNotFoundError: No module named 'open_clip'
```
    
Manually attaching to the container and running `pip install open_clip_torch` fixes the issue, likely need to add it in `requirements.txt`

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kbekus** [comment]
I had this issue too and added this line in requirements.txt which seems to have fixed it.

open-clip-torch==1.2.1
