### ISSUE TITLE
[Bug]: No submit button after last update in streamlit

### ISSUE THREAD

**Issue by xor7589** [sd-webui/stable-diffusion-webui#1456]
### What happened?

A bug happened!
After last update submit button vanished.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Where are you running the webui?

Windows

### Relevant log output

```shell
Missing Submit Button

This form has no submit button, which means that user interactions will never be sent to your Streamlit app.

To create a submit button, use the st.form_submit_button() function.

For more information, refer to the documentation for forms.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dineshdharme** [comment]
I am facing the same issue. It works the first time. But then this error pops up.

**Comment by PandaBalls** [comment]
Remember to modify the custom config file under "stable-diffusion-webui\configs\webui\userconfig_streamlit.yaml". This will contain the String Value of steps setting , still cause the same type error.

**Comment by yourcount** [comment]
I had the same issue. If you save settings in the streamlit web UI, it will override the following file:"stable-diffusion-webui\configs\webui\userconfig_streamlit.yaml" In this file, on line 70, you find that step has the value "10". You should remove the quotation marks and save the file. Your error should be gone now. 

Be warned: When you update your settings, this will override the file. You should then remove the quotation marks and you're good to go.
