### ISSUE TITLE
How to specify GPU|怎么指定特定显卡运行

### ISSUE THREAD

**Issue by GoldenDog1218** [sd-webui/stable-diffusion-webui#1510]
i have p106-100 and gtx 970 how to specify GPU
我有p106-100和gtx970显卡 我该怎么指定特定显卡运行

**Comment by AaronWebster** [comment]
If you're talking about the error you get when trying to run the docker, make sure you install the correct docker for your GPU.  For example `nvidia-docker2` from https://nvidia.github.io/nvidia-docker/ and then `systemctl restart docker`.

**Comment by GoldenDog1218** [comment]
sorry i don't see “Selectable GPU usage with --gpu <id>”
