### ISSUE TITLE
How to listen both IPv6&v4 ?如何在运行时监听ipv6和v4地址？

### ISSUE THREAD

**Issue by qeqeq1** [sd-webui/stable-diffusion-webui#1523]
When start with"--listen",I noticed that ,running on local url "0.0.0.0:7680"
It means,the webui only listen IPv4,How can I use IPv6 to visit webui?
I found
`server_name="0.0.0.0" if cmd_opts.listen else None,`
in webui.py。
I edit it,and then there are
`server_name="::" if cmd_opts.listen else None,`
But an error occurs when starting
我使用了--listen参数启动，我注意到程序提示在本地url 0.0.0.0：7680运行，这意味着他只监听了ipv4
我该如何使用IPv6进行连接？我发现了`server_name="0.0.0.0" if cmd_opts.listen else None,`
in webui.py，我将其修改为`server_name="::" if cmd_opts.listen else None,`
启动时出现报错

**Comment by codedealer** [comment]
This concerns Gradio's handling of the server. 
You can refer to their repo https://github.com/gradio-app/gradio and create an issue there if needed
