### ISSUE TITLE
[Bug]: TypeError: __init__() got an unexpected keyword argument 'elem_id'

### ISSUE THREAD

**Issue by Anyeos** [sd-webui/stable-diffusion-webui#1558]
### What happened?

```
Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
Found LDSR
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "scripts/webui.py", line 2558, in <module>
    demo = draw_gradio_ui(opt,
  File "stable-diffusion-webui/frontend/frontend.py", line 68, in draw_gradio_ui
    with gr.Column(elem_id="text2img_col2"):
TypeError: __init__() got an unexpected keyword argument 'elem_id'
```

### Version

0.0.1 (Default)

### Where are you running the webui?

Linux

### Custom settings

```shell
No custom settings only updated yesterday with linux-sd.sh
Before yesterday it was working well.
And of course, I updated today but the same error.
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "scripts/webui.py", line 2558, in <module>
    demo = draw_gradio_ui(opt,
  File "stable-diffusion-webui/frontend/frontend.py", line 68, in draw_gradio_ui
    with gr.Column(elem_id="text2img_col2"):
TypeError: __init__() got an unexpected keyword argument 'elem_id'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adamenger** [comment]
Not a proper fix but reverting the change to `with gr.Column():` from `with gr.Column(elem_id="text2img_col2"):` on line 68 in `frontend/frontend.py` lets the UI boot at least.

**Comment by codedealer** [comment]
@Anyeos hello, it looks like your environment was not updated correctly. Make sure running
`pip show gradio`
in your conda prompt shows version 3.4.1

**Comment by nixodmin** [comment]
> Not a proper fix but reverting the change to `with gr.Column():` from `with gr.Column(elem_id="text2img_col2"):` on line 68 in `frontend/frontend.py` lets the UI boot. Anybody running `webui.cmd` will be seeing this issue since it auto updates.

Thanx a lot man, this temporary solves problem.

**Comment by nixodmin** [comment]
> @Anyeos hello, it looks like your environment was not updated correctly. Make sure running `pip show gradio` in your conda prompt shows version 3.4.1

Very appreciate if is there more detailed explanation how to do it in windows. Lots of people have no idea what to do then such problem happens, they just watch youtube, install stable diffusion step by step, and thats all.

**Comment by codedealer** [comment]
1. Open anaconda prompt (type in your windows searchbar "anaconda powershell" and it should appear)
![image](https://user-images.githubusercontent.com/4258136/197212739-0036ef18-0609-4adf-ab4c-a405bcc4e837.png)
2. in the prompt type `conda activate ldm` (if you didn't change the name of the env)
3. `pip show gradio`

It should display the info about the package, which should say that it's 3.4.1. If you're running an older version the error about elem_id can pop up because this functionality is new. In which case you have to update your env by deleting z.tmp file or just installing a proper version of gradio manually.

**Comment by Anyeos** [comment]
Hi, actually the error is gone. It appears to be fixed in recent updates. And now the entire environment was updated. But before it doesn't, so maybe that is relevant (it don't give me really choice to test it because it was solved instantly after the last update). 

For now it is working well.

Thank you for your help and to make this project, it helps me as artist.

**Comment by nixodmin** [comment]
> update your env by deleting z.tmp file

Thanx a lot! This helped.
