### ISSUE TITLE
[Bug]: Key "keep_all_models_loaded" not exists exception in /scripts/sd_utils.py.

### ISSUE THREAD

**Issue by cyruschan360** [sd-webui/stable-diffusion-webui#1572]
### What happened?

Key "keep_all_models_loaded" not exists exception in /scripts/sd_utils.py.

Please patch line 150:
from
if "keep_all_models_loaded" in st.session_state:
to
if "keep_all_models_loaded" in st.session_state["defaults"].general:

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ZeroCool940711** [comment]
This has been fixed on the dev branch already, please wait for the next merge or switch branches to the dev branch which is where active development happens and the latest features are.
