### ISSUE TITLE
[FEATURE REQUEST] Option to use the image's alpha channel or a separate grayscale image as mask

### ISSUE THREAD

**Issue by TiagoTiago** [sd-webui/stable-diffusion-webui#372]
**Is your feature request related to a problem? Please describe.**
Sometimes you might wanna use the more advanced tools from an external editor to produce a more detailed mask; or have more control over varying masking intensities (how far from the original image should the produced result be).

**Describe the solution you'd like**
A checkbox to enable using the alpha channel as mask (useful when loading PNGs with built-in transparency); and for JPGs (and whatever other formats are supported that don't have alpha support), a button to open a second image area where you can load/drop another image file, which will be treated as being grayscale, with white being fully unsmaked and black fully masked, and intermediary values in between.

The existing "Mask Mode" option would work to invert the interpretation of the provided masks.

**Comment by vinyvince** [comment]
Is there any hope to make the drawing mask better please? It's very slow, capricious, can't do much.... i will also prefer to have the possibility to load a mask ... Cheers everyone, warm my heart to see the world unit for progress, i wish everything could be solved like that...

**Comment by rpetti** [comment]
What I don't quite understand is that the Hints section of the img2img UI states that you should do masking in an external editor, but doesn't explain _how_.
