### ISSUE TITLE
[Bug]: Same problem as issue #194 - No image in webui (intermittently)

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [sd-webui/stable-diffusion-webui#462]
### What happened?

After a few runs, the txt2img images stop appearing in the web UI. When it happens, the only way I can restore it is to stop the server and re-open the web page. I think it happens after using text2img, then using the Image lab to face fix and then back to txt2img, but not reliably, so may have been a coincidence.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjisnow** [comment]
Related to [493](https://github.com/hlky/stable-diffusion-webui/issues/493)
