### ISSUE TITLE
[Bug]: Masking image regeneration is no longer working?

### ISSUE THREAD

**Issue by AmoArt** [sd-webui/stable-diffusion-webui#477]
### What happened?

In the new version the masking is no longer working for me, whenever I try to run it it shows me error that the model is out of memory (the masking function worked just fine in the previous version).

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ehplodor** [comment]
![image](https://user-images.githubusercontent.com/80175881/188116669-53cc3a5f-7e64-4bd1-8f20-ec2a5bba5a5a.png)
the masking - regenerate only masked areas, is not working for me. as if mask is not taken into account at all. While keep only masked area seems fine

**Comment by jjisnow** [comment]
I think there's crop or "uncrop" modes which result in a fill of masked areas

**Comment by Ehplodor** [comment]
Fresh install a few minutes ago. mask - regenerate only masked areas still not working at all. Am I missing something ?

**Comment by jjisnow** [comment]
#632

**Comment by codedealer** [comment]
Fixes have been merged to master
