### ISSUE TITLE
[Bug]: GFPGAN and RealESRGAN does not work in txt2img tab

### ISSUE THREAD

**Issue by VeyDlin** [sd-webui/stable-diffusion-webui#482]
### What happened?

If you check the RealESRGAN or GFPGAN in Advanced settings, the generation does not work

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by OriginalJohann** [comment]
I've the same issue. The images aren't generated. The terminal shows no error after generating the image and the imagedisplay in the GUI shows a placeholder.

**Comment by VeyDlin** [comment]
Yes, I checked and the files are being created

**Comment by malistaticy** [comment]
same issue, the images are being generated and dropped in the output samples folder, but the webui will not display them at all if either setting is enabled. kinda tedious to have to navigate through the folders

**Comment by OriginalJohann** [comment]
Mine won't even be saved (saving option is checked). Only the generation-process is running

**Comment by jjisnow** [comment]
#503 #500

**Comment by p-somers** [comment]
Looks like it has to do with the fact that `skip_save` is getting explicitly set to `True` if you have either GFPGAN or RealESRGAN enabled (starting on line 889):

```python
                if use_GFPGAN and GFPGAN is not None and not use_RealESRGAN:
                    skip_save = True # #287 >_>
                    ...

                if use_RealESRGAN and RealESRGAN is not None and not use_GFPGAN:
                    skip_save = True # #287 >_>
                    ...

                if use_RealESRGAN and RealESRGAN is not None and use_GFPGAN and GFPGAN is not None:
                    skip_save = True # #287 >_>

                #if imgProcessorTask == True:
                #    output_images.append(image)

                if not skip_save:
                    save_sample(...)
                    if add_original_image or not simple_templating:
                        output_images.append(image)
```

Does anyone know why the `imgProcessorTask == True` check got commented out?

**Comment by p-somers** [comment]
Not really sure if the issue is related, but here's bug #287 https://github.com/hlky/stable-diffusion-webui/issues/287
