### ISSUE TITLE
[Bug]: Masking does not work correctly for aspect ratios different than 1:1

### ISSUE THREAD

**Issue by xvel** [sd-webui/stable-diffusion-webui#495]
### What happened?

Looks like masking does not work correctly for aspect ratios different than 1:1, mask is applied in different place than it is drawn.

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Goldenkoron** [comment]
Let me restate as well that this bug is separate from the one where the mask tool visually looks offset until you zoom out and back in. In this case the mask looks correct in gradio but the output image gets affects as if the mask were invisibly offset on wider aspect ratios.

**Comment by AdamNizol** [comment]
I mentioned the same thing and he closed it an hour ago saying that the editor is buggy and to use photoshop. Apparently there is some way to add the mask manually but I asked him how since the docs dont seem to explain it. Might just be using the opacity channel as a mask but I'm not sure yet.
