### ISSUE TITLE
[Bug]: Moved and removed batch_size options

### ISSUE THREAD

**Issue by nderscore** [sd-webui/stable-diffusion-webui#521]
### What happened?

* #421 moved the batch size slider on the txt2img tab into the advanced options
  * As someone who uses the batch_size option regularly, this change is a bit of a nuisance. 
  * Depending on the dimensions of images I'm rendering, I'm frequently changing my batch size at the same time (gotta max my VRAM utilization 😎 )
  * Previously, these settings were conveniently colocated in the same block, but now I have to jump back and forth across the screen (and open the advanced settings tab)
* #468 removed the batch size slider outright from the img2img tab
  * This is even worse - I can't change the batch size anymore at all on this workflow now :(

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
As an author of #468 I'd like to point out that I didn't remove the slider, I merely fixed a bug that was introduced when it was removed.

As for text2img tab, the rationale was that having `batch count` and `batch size` together was confusing so the memory hungry and potentially dangerous one was moved.

As a side note, if you're changing `batch_size` constantly why not do it directly in prompt with an argument?

**Comment by nderscore** [comment]
> I'd like to point out that I didn't remove the slider

Sorry for wrongly attributing!

> As a side note, if you're changing batch_size constantly why not do it directly in prompt with an argument?

I've disabled that feature because it introduces lag (and because I fundamentally disagree it's existence, due to how easily it will [destroy prompts that contain words matching the parameter names](https://github.com/hlky/stable-diffusion-webui/pull/421#issuecomment-1234245138))

**Comment by altryne** [comment]
>I've disabled that feature  

?

**Comment by nderscore** [comment]
> ?

locally! :sweat_smile:

**Comment by altryne** [comment]
> As someone who uses the batch_size option regularly, this change is a bit of a nuisance.

SORRY! 
This was confusing me and it's now much simpler
