### ISSUE TITLE
[Bug]: If i use webui.py for cli it runs out of memory faster?

### ISSUE THREAD

**Issue by devingDev** [sd-webui/stable-diffusion-webui#557]
### What happened?

Opening the webui normally ("Start Full Speed.cmd"), I can make up to 704x704 pictures in txt2img (tested: k_lms, k_dpm_a2, 50steps)
but if I try to do it from cli i run out of memory even on 640x640, i can go only up to 576x576
Also what I noticed its just using a lot more VRAM that way and idk why..

Task manager says these vram values:
[webui] 704x704 picture VRAM 6.9/8.0 GB 
[cli] 576x576 picture VRAM 7.3/8.0 GB

example command: python webui.py --cli txt2img.yaml

This is very weird and idk how the webui can "save" more vram??

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HenkDz** [comment]
where did you find the "Start Full Speed.cmd" file? can you share please?

**Comment by devingDev** [comment]
Ah my bad ... I forgot to mention its from the installation pack found here (its so confusing having all these sd installations lol) 
https://rentry.org/guitard
where it says "(Updated 8/29) Alternate Prepack Installer available Here"

that file pretty much just calls another file after making a B: drive
@echo off
subst /D B:
subst B: "%~dp0"
cd /d B:\
call webui_runtime

which in turn also does some set up stuff and calls python scripts/relauncher.py



I sent webui.py too in case something is different, but like i dont get it why this vram diff happens?



[Start Full Speed.cmd.txt](https://github.com/hlky/stable-diffusion-webui/files/9482405/Start.Full.Speed.cmd.txt)
[webui_runtime.cmd.txt](https://github.com/hlky/stable-diffusion-webui/files/9482406/webui_runtime.cmd.txt)
[relauncher.py.txt](https://github.com/hlky/stable-diffusion-webui/files/9482408/relauncher.py.txt)
[webui.py.txt](https://github.com/hlky/stable-diffusion-webui/files/9482412/webui.py.txt)
