### ISSUE TITLE
[Bug] "Send to Lab" Uses Incorrect Seed

### ISSUE THREAD

**Issue by KyuubiYoru** [sd-webui/stable-diffusion-webui#579]
### What happened?

The "Send to Lab" button uses the seed from the first image instead of the selected image. 
This also occurs with the "Copy all" and "Copy seed" buttons.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devilismyfriend** [comment]
Currently I'm not sure there's a way to retrieve the selected image parameters as they're not kept in memory @altryne might know more

**Comment by KyuubiYoru** [comment]
Looks like the seed of the selected image is base seed + image index, not sure if thats always the case.

**Comment by altryne** [comment]
> Currently I'm not sure there's a way to retrieve the selected image parameters as they're not kept in memory @altryne might know more

Pain in the ass to "grab" the seed unfortunately. We can manually increment but it won't still be enough cause there's a variance seed, and seeds change according to if you use batch_size or not. 

I'm open to ideas, the way I'm "grabbing" the current library image is just by CSS, I wish we were able to send descriptions back with the image, or maybe encode in PNG the paramters + seed (I think we do, but not sure how to extract them clientside)

**Comment by devilismyfriend** [comment]
> > Currently I'm not sure there's a way to retrieve the selected image parameters as they're not kept in memory @altryne might know more
> 
> Pain in the ass to "grab" the seed unfortunately. We can manually increment but it won't still be enough cause there's a variance seed, and seeds change according to if you use batch_size or not.
> 
> I'm open to ideas, the way I'm "grabbing" the current library image is just by CSS, I wish we were able to send descriptions back with the image, or maybe encode in PNG the paramters + seed (I think we do, but not sure how to extract them clientside)

Does the CSS index happen incrementally? like, is it consistent with generation? if so we can store the values used in batches in memory and match it if the user wants to push settings somewhere else.

Anyway this isn't an easy ask right now, just fyi op.

**Comment by codedealer** [comment]
My question is: are the seeds for all the elements in the gallery stored somewhere in gradio or do they have to be inferred?

It's easy to get the selected image from the gallery (via CSS selectors, true but it works). If the whole list of parameters for each image generated is/can be stored somewhere it should be relatively easy to implement.

**Comment by rasteiner** [comment]
Just a workaround for people finding this on google. 

If you keep the images in the `\outputs\txt2img-samples\samples\`, each image is saved with the seed in the filename. Like:
for the image `00020-10_k_lms_1311457498_0.00.png`, the seed would be `1311457498`. I know this isn't a solution, but its the easiest way to find out about an image seed I've found.
