### ISSUE TITLE
[Bug]: Problems with the launch "(Updated 8/29) Alternate Prepack Installer"

### ISSUE THREAD

**Issue by sashaok123** [sd-webui/stable-diffusion-webui#605]
### What happened?

"(Updated 8/29) Alternate Prepack Installer"
An error occurs at startup "Start (Full Speed/Low Memory)" and a cyclical restart occurs.

![2022-09-04_06-35-00](https://user-images.githubusercontent.com/27728380/188293370-c392909b-6bb3-496c-b157-e6cdc19e8198.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
ModuleNotFoundError: No module named 'frontend'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...
        Relaunch count: 1141
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
ModuleNotFoundError: No module named 'frontend'
Relauncher: Process is ending. Relaunching in 0.5s...
Relauncher: Launching...
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Chadius** [comment]
I uninstalled miniconda and reinstalled, selecting the "Add miniconda to path" option (the one that the installer says isn't recommended.)

The problem now is that `script/webui.py`'s path does not have miniconda's environment on its path, so it doesn't see the `frontend` folder. The anaconda `environment.yaml` script needs to add this to the path OR the instructions should be updated to check the "Add miniconda to path" option

I'm not an anaconda expert, so hopefully the devs can tackle this.

**Comment by iFrostizz** [comment]
> 

This didn't do the trick :/

**Comment by iFrostizz** [comment]
> I uninstalled miniconda and reinstalled, selecting the "Add miniconda to path" option (the one that the installer says isn't recommended.)
> 
> The problem now is that `script/webui.py`'s path does not have miniconda's environment on its path, so it doesn't see the `frontend` folder. The anaconda `environment.yaml` script needs to add this to the path OR the instructions should be updated to check the "Add miniconda to path" option
> 
> I'm not an anaconda expert, so hopefully the devs can tackle this.

This didn't do the trick :/
