### ISSUE TITLE
rinongal/textual_inversion trained embeddings crash upon usage

### ISSUE THREAD

**Issue by silverogar** [sd-webui/stable-diffusion-webui#606]
### What happened?

Trained a embeddings.pt on the advised repo (https://github.com/rinongal/textual_inversion)
Note: https://github.com/hlky/sd-enable-textual-inversion makes a reference to a v1-finetune.yaml file, but no such file is found in either repo.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Relevant log output

```shell
shape mismatch: value tensor of shape [1280] cannot be broadcast to indexing result of shape [0, 768]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hlky** [comment]
>v1-finetune.yaml 

It's in rinongal's repo, you must have used it to do the training. The file is unrelated to inference anyway.

`shape mismatch: value tensor of shape [1280] cannot be broadcast to indexing result of shape [0, 768]`

You will need to share your embeddings for me to investigate this.

**Comment by simcop2387** [comment]
I had this exact error with the anya.pt from https://github.com/hlky/sd-embeddings I'm currently trying to train my own and will update here if success or different error.
