### ISSUE TITLE
[Bug]: image-to-image won't run. TypeError: string indices must be integers

### ISSUE THREAD

**Issue by feelie75** [sd-webui/stable-diffusion-webui#610]
### What happened?

I JUST downloaded the repo .zip only an hour ago for both stable-diffusion-main and stable-diffusion-webui. I just installed anaconda an hour ago, newest version.

I copied the *.py files from the webui main folder into the stable-diffusion-main/scripts/ folder as instructed by this youtube tutorial (https://www.youtube.com/watch?v=bu2xwx-6JGk), I generate a text-to-image image, click Push to img2img, then I click Generate on that tab, and it creates these errors:

Traceback (most recent call last):
  File "C:\Users\adubr\anaconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\adubr\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\adubr\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\adubr\anaconda3\envs\ldm\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
Couldn't find job FuncKey(job_id=UUID('3590e32e-4f70-4bb6-9d8b-fb98d532626d'), func=<function img2img at 0x00000238EDF86B80>) in session "595ebd61422b4371b39f188b21d31c88"
Couldn't find job FuncKey(job_id=UUID('3590e32e-4f70-4bb6-9d8b-fb98d532626d'), func=<function img2img at 0x00000238EDF86B80>) in session "595ebd61422b4371b39f188b21d31c88"

Like I said, I JUST downloaded everything an hour ago, so I should have the most current version, right? Thanks!

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\adubr\anaconda3\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\adubr\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\adubr\anaconda3\envs\ldm\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\adubr\anaconda3\envs\ldm\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
Couldn't find job FuncKey(job_id=UUID('3590e32e-4f70-4bb6-9d8b-fb98d532626d'), func=<function img2img at 0x00000238EDF86B80>) in session "595ebd61422b4371b39f188b21d31c88"
Couldn't find job FuncKey(job_id=UUID('3590e32e-4f70-4bb6-9d8b-fb98d532626d'), func=<function img2img at 0x00000238EDF86B80>) in session "595ebd61422b4371b39f188b21d31c88"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by feelie75** [comment]
Reading the old closed issues of this happening, the work-around still works: Click MASK, then click 'x' to clear the mask, then click back to CROP, then click generate and that fixes the problem, no errors when I do that work-around.

**Comment by TFWol** [comment]
> Reading the old closed issues of this happening, the work-around still works: Click MASK, then click 'x' to clear the mask, then click back to CROP, then click generate and that fixes the problem, no errors when I do that work-around.

Thanks, this worked for me.

**Comment by codedealer** [comment]
Investigating

**Comment by hlky** [comment]
Been investigating this, it seems to be a ui issue related to the 2 different gr.Image, how they are given to the functions, and possibly something related to the default image

My changes so far: https://github.com/hlky/stable-diffusion-webui/tree/img2img-fix

If you could test and report back I can get this merged

What works:

* Loading image to crop
![image](https://user-images.githubusercontent.com/106811348/188314882-833d3216-98a0-41d9-b6e2-ca1687d48a1d.png)

* Keep masked area
![image](https://user-images.githubusercontent.com/106811348/188314901-5c3c45d1-823f-4730-b86c-1799edb7a4d3.png)
![image](https://user-images.githubusercontent.com/106811348/188314916-d382378e-8607-4d64-8817-8219aac36846.png)

* Regenerate masked area
![image](https://user-images.githubusercontent.com/106811348/188314926-d717c09d-050c-4ef9-a74d-3e906d02034d.png)
![image](https://user-images.githubusercontent.com/106811348/188314933-153f82e5-28f6-447d-b974-9a645d3bcf35.png)

What doesn't work:
Switching crop -> mask doesn't move the image
???

Untested: 
"Uncrop" mode

**Comment by hlky** [comment]
@feelie75 
>I copied the *.py files from the webui main folder into the stable-diffusion-main/scripts/ folder as instructed by this youtube tutorial (https://www.youtube.com/watch?v=bu2xwx-6JGk)
Would be better if tutorials didn't go against the very clear instructions to not use the dev repo directly though 🤷

**Comment by telemole** [comment]
I tried this im2img-fix branch and I'm still getting errors on anything I try to generate in img2img : 

sd                  | Traceback (most recent call last):
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
sd                  |     output = await app.blocks.process_api(
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
sd                  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
sd                  |     processed_input.append(block.preprocess(raw_input[i]))
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1563, in preprocess
sd                  |     mask_im = processing_utils.decode_base64_to_image(mask)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/processing_utils.py", line 28, in decode_base64_to_image
sd                  |     content = encoding.split(";")[1]
sd                  | AttributeError: 'NoneType' object has no attribute 'split'

**Comment by codedealer** [comment]
I think you're just running it with empty prompt which is not supported

**Comment by telemole** [comment]
I wish it were that simple :( 

> I think you're just running it with empty prompt which is not supported

but there is indeed a prompt : this is from a fresh launch : 
![image](https://user-images.githubusercontent.com/22926791/188328709-77e1a59e-649b-4396-a4d4-0f40c70fbefa.png)

as soon as I press generate the console produces the following : 
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
sd                  |     output = await app.blocks.process_api(
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
sd                  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
sd                  |     processed_input.append(block.preprocess(raw_input[i]))
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1563, in preprocess
sd                  |     mask_im = processing_utils.decode_base64_to_image(mask)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/processing_utils.py", line 28, in decode_base64_to_image
sd                  |     content = encoding.split(";")[1]
sd                  | AttributeError: 'NoneType' object has no attribute 'split'

**Comment by telemole** [comment]
I've done a complete re-install - brought over the new branch files - txt2img works, but img2img (with prompt) : 
![image](https://user-images.githubusercontent.com/22926791/188329815-f7c4be82-2796-46ef-a9af-758cb508e69c.png)

fails and console has same errors : 
sd                  | Traceback (most recent call last):
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
sd                  |     output = await app.blocks.process_api(
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 639, in process_api
sd                  |     processed_input = self.preprocess_data(fn_index, raw_input, state)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/blocks.py", line 543, in preprocess_data
sd                  |     processed_input.append(block.preprocess(raw_input[i]))
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/components.py", line 1563, in preprocess
sd                  |     mask_im = processing_utils.decode_base64_to_image(mask)
sd                  |   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/gradio/processing_utils.py", line 28, in decode_base64_to_image
sd                  |     content = encoding.split(";")[1]
sd                  | AttributeError: 'NoneType' object has no attribute 'split'

**Comment by mchaker** [comment]
There is a fix in the `img2img-fix` branch. See comment: https://github.com/hlky/stable-diffusion-webui/issues/664#issuecomment-1237025304

**Comment by codedealer** [comment]
fixes have been merged to master
