### ISSUE TITLE
[Bug]: UI Issues (Copy Paste, Advanced Tab broken)

### ISSUE THREAD

**Issue by ShaneBurke** [sd-webui/stable-diffusion-webui#622]
### What happened?

When copy pasting into dream prompt field text will immediately disappear and generate button will become larger. Following this if the field is pasted again and generate is clicked nothing happens. UI works for submitting generation only when manually typing prompt. Following this happening Advanced tab is also broken even after restarting the webui from console, refreshing page, and clearing temp internet files from browser.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by helgur** [comment]
Same issue
