### ISSUE TITLE
[Bug]: error message in init

### ISSUE THREAD

**Issue by TwistedFromArma** [sd-webui/stable-diffusion-webui#642]
### What happened?

A bug happened!

LDSR not found at path, please make sure you have cloned the LDSR repo to ./src/latent-diffusion/

using current webui version.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Relevant log output

```shell
Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
LDSR not found at path, please make sure you have cloned the LDSR repo to ./src/latent-diffusion/
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by telemole** [comment]
this sorted me out for LDSR : 

https://github.com/hlky/stable-diffusion-webui/discussions/450#discussioncomment-3530911

**Comment by TwistedFromArma** [comment]
thats exactly whats needed. ty
