### ISSUE TITLE
[Bug]: Only the GFPGAN image is saved.

### ISSUE THREAD

**Issue by ZeroCool22** [sd-webui/stable-diffusion-webui#658]
### What happened?

I think we should have the choice to say if we want the GFPGAN and Normal image too.

💡 Because sometimes we want to mix parts of both images in a post process like Photoshop, happens a lot of times, that **some part of the same image** looks better in one version than another, so i **mix both** and keep the best parts of both in one image, i hope you understand what i mean.

This is what i mean:

Before the update, we got the **2** images versions:

![Both versions](https://user-images.githubusercontent.com/13344308/188353238-84efe85e-f6c3-4015-9992-68314fd81af1.jpg)

Now we only get the **GFPGAN**: 

![Screenshot_2](https://user-images.githubusercontent.com/13344308/188353263-628c1d37-5a8b-40a5-8a40-c874dbd54774.jpg)

👉 **PD:** There is some part of the code i can modify to get both versions of the image?

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Custom settings

```shell
No.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjisnow** [comment]
While waiting, you can simply remove ' skip_save=True' at line 971, 985 and elsewhere in the code and it should fix it

**Comment by ZeroCool22** [comment]
> skip_save

Sorry, in what file exactly i remove it?

Thx!

**Comment by jjisnow** [comment]
Yes

**Comment by ZeroCool22** [comment]
> > > skip_save
> > 
> > 
> > Sorry, in what file exactly i remove it?
> > Thx!
> > **EDIT:**
> > Found it!
> 
> Is it webui.py?

Yes.
