### ISSUE TITLE
[Bug]: Version #308 caused mask painting to start changing color of images and introduce purple abberations

### ISSUE THREAD

**Issue by Goldenkoron** [sd-webui/stable-diffusion-webui#659]
### What happened?

Sorry if this isn't a clean bug report, it's my first one here. I was on a version from 8/30 and updated to latest version and discovered an issue that's been present since all the way back to this version https://github.com/hlky/stable-diffusion-webui/pull/308

The issue as I would describe it is any output image in img2img even if you're not using the mask or changing the original image at all will have its contrast boosted about 10-20% and purple spots start to appear. If someone is using img2img to repeatedly enhance an image or fix issues with the mask tool the image will inevitably become extremely over contrasted and full of purple spots within 10 iterations.

I attached some screenshots to illustrate this issue over multiple img2img runs.

![5](https://user-images.githubusercontent.com/112432266/188355620-c5dd3a18-fdf0-4353-92a4-7f2ae4d9d751.png)

![6c](https://user-images.githubusercontent.com/112432266/188355655-6b963062-2bf4-43fa-8fd3-7ee4089d5156.png)

![7](https://user-images.githubusercontent.com/112432266/188355673-5b88a1ec-a6c1-4f30-9854-4dc017f51ce7.png)

![8](https://user-images.githubusercontent.com/112432266/188355691-355343f2-8193-41be-adc1-b33b8f21fe9e.png)

![9](https://user-images.githubusercontent.com/112432266/188355702-70886522-02cc-4bb1-ae50-5bc74d0ea164.png)

### Version

0.0.1 (Default)

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mchaker** [comment]
There is a fix in the `img2img-fix` branch. See comment: https://github.com/hlky/stable-diffusion-webui/issues/664#issuecomment-1237025304
