### ISSUE TITLE
[Bug]: img2img does not work because "string indices must be integers"

### ISSUE THREAD

**Issue by vivredraco** [sd-webui/stable-diffusion-webui#674]
### What happened?

When I click the generate button in the img2img tab, nothing happens in the web UI and I get the attached error in the console. I have tried multiple times with different images and tried restarting webui.cmd, but it consistently fails with the same error.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "<userpath>\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 2
47, in run_predict
    output = await app.blocks.process_api(
  File "<userpath>\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 6
39, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "<userpath>\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 5
43, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "<userpath>\.conda\envs\ldo\lib\site-packages\gradio\components.py", li
ne 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThompZon** [comment]
I have the same issue

**Comment by xieve** [comment]
This workaround works for me: Image Editor → Mask → Draw anything → Crop → Generate

**Comment by vivredraco** [comment]
Thanks @xieve, that works for me with standard input images, which is a huge help. However, if I attempt to draw something using the Advanced Editor button, I seem to get this error even if I follow the workaround above.

**Comment by ThompZon** [comment]
So I tried the following
1. Start
2. press generate
3. Push to img2img
4. press generate
5. Get error from Original Post
6. Press mask
7. Draw anything
8. Back to crop
9. Press generate
10. Success

**Comment by Asmor** [comment]
Have same problem. @xieve's workaround works for me, at least.

**Comment by Jonseed** [comment]
Same issue. @xieve's workaround worked for me too.

**Comment by Vyviel** [comment]
What if I want to mask or is masking broken?

**Comment by mchaker** [comment]
This does not work for me

**Comment by bbecausereasonss** [comment]
Traceback (most recent call last):
  File "C:\Users\chlyw\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\chlyw\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 639, in process_api
    processed_input = self.preprocess_data(fn_index, raw_input, state)
  File "C:\Users\chlyw\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 543, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\chlyw\.conda\envs\ldo\lib\site-packages\gradio\components.py", line 1546, in preprocess
    x, mask = x["image"], x["mask"]
TypeError: string indices must be integers

**Comment by mchaker** [comment]
There is a fix in the `img2img-fix` branch. See comment: https://github.com/hlky/stable-diffusion-webui/issues/664#issuecomment-1237025304

**Comment by Theagainmen** [comment]
The workaround doesn't work for me, it throws another error:

`ValueError: could not convert string to float: '376666e9658040a4931fca9f394b58f1'`

**Comment by vinyvince** [comment]
Same issue before, while it was working fine in earlier version. It wast everything ... (oh and of course gradio mask drawing is a nightmare :) )

**Comment by vinyvince** [comment]
I also try the repo with the supposed fix, unzipped the new repo on the old one, but that didn't solve the issue in my case... 

> img2img-fix

**Comment by MingStar** [comment]
I had the same problem, too, now I cannot draw the mask

**Comment by khronimo** [comment]
having same issue, workaround does get it to generate though.

**Comment by Hafiidz** [comment]
There is a PR coming https://github.com/sd-webui/stable-diffusion-webui/pull/753, but might need some minor revision to fully resolved this

**Comment by rmeyer-redwood** [comment]
still not resolved, even with pulling the latest version of webui from git.

**Comment by codedealer** [comment]
pull from here https://github.com/sd-webui/stable-diffusion-webui/tree/img2img-dev

**Comment by vinyvince** [comment]
Cheers, it seems to work again now like it used to be , great! :)

**Comment by codedealer** [comment]
Changes from img2img are on master branch!
