### ISSUE TITLE
[Bug]: Prompt form very unresponsive after image generation

### ISSUE THREAD

**Issue by HanJammer** [sd-webui/stable-diffusion-webui#676]
### What happened?

I have the latest webui. After generating a first set of images the prompt form becomes super unresponsive - adding or removing some words takes time and it makes a big load on the CPU.
I'm pretty sure it's related to showing the thumbnails of generated and upscaled images (in previous version I used when I used upscaling - no thumbnails were visible which I actually preferred anyway) because refreshing the browser which cleans thumbnail preview - solves the issue.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
# USER CHANGABLE ARGUMENTS

# Change to `True` if you wish to enable these common arguments

# Run upscaling models on the CPU
extra_models_cpu = True

# Automatically open a new browser window or tab on first launch
open_in_browser = False

# Run Stable Diffusion in Optimized Mode - Only requires 4Gb of VRAM, but is significantly slower
optimized = False

# Run in Optimized Turbo Mode - Needs more VRAM than regular optimized mode, but is faster
optimized_turbo = True

# Creates a public xxxxx.gradio.app share link to allow others to use your interface (requires properly forwarded ports to work correctly)
share = False


# Enter other `--arguments` you wish to use - Must be entered as a `--argument ` syntax
additional_arguments = ""
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zweifuchs** [comment]
Same problem here. It gets worse the more images you create. I frequently do batches of 42 images and the prompt becomes unbearable unresponsive.

**Comment by HanJammer** [comment]
> Same problem here. It gets worse the more images you create. I frequently do batches of 42 images and the prompt becomes unbearable unresponsive.

^ this.

Interesting thing is it only affects the prompt form field. No other fields are affected at all.

**Comment by cobryan05** [comment]
The Gradio gallery seems to pull down the entire system with it if there are high-resolution images in it. Are you upscaling as part of the batch process? If those upscaled images end up in the gallery I'd bet that's where the issue is.

**Comment by HanJammer** [comment]
> The Gradio gallery seems to pull down the entire system with it if there are _any_ high-resolution images in it. Are you upscaling as part of the batch process? If those upscaled images end up in the gallery I'd bet that's where the issue is.

They end up in the gallery, yes, but everything is fine until I try editing the prompt - if such pics are in the gallery - it just works horribly slow and hits CPU with some heavy load. I don't really see any reason why it would do that.

**Comment by ujl123** [comment]
following up on this to add that this happens with firefox as well. And all other prompt and button fields are fine, just that when you try and edit the prompt field it slows to a crawl

**Comment by cobryan05** [comment]
Looks like there is a 'live_prompt_params' function that runs every character typed in that prompt box. Maybe try going to frontend/frontend.py and commenting out/removing

```
                live_prompt_params = [txt2img_prompt, txt2img_width, txt2img_height, txt2img_steps, txt2img_seed, txt2img_batch_count, txt2img_cfg]
                txt2img_prompt.change(
                    fn=None,
                    inputs=live_prompt_params,
                    outputs=live_prompt_params,
                    _js=js_parse_prompt
                )
```

and see if that makes the issue go away.

**Comment by chris-echoz** [comment]
Looks like commenting out the lines @cobryan05 suggested makes the prompt fast again, but I'm not sure if it had any side effects

**Comment by ujl123** [comment]
> Looks like commenting out the lines @cobryan05 suggested makes the prompt fast again, but I'm not sure if it had any side effects

agreed, the live_prompt_params being commented out does make it better, but I don't know what effect it has as well. In use, I don't see any difference or errors,.

**Comment by codedealer** [comment]
@ujl123 @chris-echoz 
`live_prompt_params` allows to pass arguments you would normally pass to the cli (like --cfg, --batch_size etc.) directly to the prompt. It's nothing critical and looks like people are not even aware it's there.

**Comment by micwalk** [comment]
See also previous discussion of this in the old repo: https://github.com/sd-webui/stable-diffusion/issues/220

Root cause is a gradio bug here: https://github.com/gradio-app/gradio/issues/2159

I think until the root cause is fixed disabling the live_prompt_params is a good solution, or migrating the param parsing to be done only on submit despite less than ideal UX.
