### ISSUE TITLE
[Bug]: LDSR not found at path

### ISSUE THREAD

**Issue by ozgur-kucuk** [sd-webui/stable-diffusion-webui#703]
### What happened?

I followed all the steps. But the LDSR folder cannot be found.

operating system: Manjaro Linux KDE edition
display card: Powercolor Red Devil AMD Radeon RX 6700 XT

### Version

0.0.1 (Default)

### Where are you running the webui?

Linux

### Custom settings

```shell
HSA_OVERRIDE_GFX_VERSION=10.3.0 python ./webui.py
```

### Relevant log output

```shell
HSA_OVERRIDE_GFX_VERSION=10.3.0 python ./webui.py
LDSR not found at path, please make sure you have cloned the LDSR repo to ./src/latent-diffusion/
Traceback (most recent call last):
  File "./webui.py", line 451, in <module>
    model, device,config = load_SD_model()
  File "./webui.py", line 441, in load_SD_model
    config = OmegaConf.load(opt.config)
  File "/home/darkshade/.conda/envs/ldm/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 183, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/darkshade/stable-diffusion/scripts/configs/stable-diffusion/v1-inference.yaml'
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by jjisnow** [comment]
Maybe try detailed instructions at https://github.com/Hafiidz/latent-diffusion or part of the brief instructions https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation
if in doubt, do a file search of your folder for `v1-inference.yaml` in case there's a misconfiguration or download to the wrong spot?
