### ISSUE TITLE
[Bug]: VRAM consumption with GFPGAN and RealESRGAN

### ISSUE THREAD

**Issue by DarkAndBlue** [sd-webui/stable-diffusion-webui#704]
### What happened?

I noticed when using GFPGAN and RealESRGAN under the advanced tab I get an CUDA out of memory error when generating the second image.

(It seems to only happen when a face is on the image to be enhanced by GFPGAN I used the same seed with Variant Amount of 0.01 to get only faces to repreduce the issue)

The prompt and seed I use to test the models:
"A photo of a woman in 1970" steps 50 sampler k_lms number 5 cfg_scale 7.5 seed 238835542 width 704 height 512

The crash happens when trying to generate the second image:
![stablediffusionerror](https://user-images.githubusercontent.com/13067258/188629616-4053169e-13f6-45f9-8c66-c41464970b62.png)

When using this https://github.com/hlky/stable-diffusion/tree/d667ff52a36b4e79526f01555bfbf85428f334ce
5 days old version everything works fine.

I also noticed when I generate a random image first with using GFPGAN and ESRGAN and then generating multiple images of my set seed with Variation Amount of 0.01 everything works fine
![image](https://user-images.githubusercontent.com/13067258/188630809-309535fd-ea69-4631-af60-3c4528760960.png)

When I need to guess I would say that some of the VRAM allocated by ESRGAN or GFPGAN doesn't get cleared when generating the next image afterwards. Maybe it also has something todo with setting the seed

My specs PC:
Graphicscard = Nvidia GTX 1070 (8GB VRAM. Stable diffusion gets me to 7.7GB usage with some programs running on the background)
CPU = Intel Core i7 6700k

### Version

0.0.1 (Default) I repreduced the error on https://github.com/hlky/stable-diffusion/commit/960b623acdef3b9a14454550cc68ad04e8d531a3

### What browsers are you seeing the problem on?

Firefox, Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
To create a public link, set share=True in launch().
Loaded GFPGAN
Loaded RealESRGAN
Iteration: 1/5
[MemMon] Recording max memory usage...

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [01:02<00:00,  1.25s/it]
Iteration: 2/5
  0%|                                                                                           | 0/50 [00:02<?, ?it/s]
!!Runtime error (txt2img)!!
 CUDA out of memory. Tried to allocate 1.89 GiB (GPU 0; 8.00 GiB total capacity; 3.85 GiB already allocated; 705.45 MiB free; 5.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
exiting...calling os._exit(0)
Relauncher: Process is ending. Relaunching in 1s...
        Relaunch count: 1
Relauncher: Launching...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mchaker** [comment]
have you tried Doggettx's memory optimization?
https://gist.github.com/mchaker/e0cf180db6849fa03696293b3fc8f485

**Comment by mchaker** [comment]
Ah, good point. My apologies.

**Comment by dudumaroja** [comment]
yes.. i could use both GANS just fine.. even with cpu.. now i just even think in enabling then or cuda goes crazy

**Comment by DarkAndBlue** [comment]
As the dev branch uses less vram now and many things changed I close the issue.

**Comment by dudumaroja** [comment]
too bad.. im in dev.. and gfpgan still wont run for me in a gtx 1660ti.. and used to work just fine
