### ISSUE TITLE
[Bug]: Textual Inversion "Upload Box" no longer appear

### ISSUE THREAD

**Issue by Onelio** [sd-webui/stable-diffusion-webui#711]
### What happened?

I think this is a bug. My installation works flawlessly, but there is no longer a "textual inversion" upload box for the model on the WebUI side. I'm using stable-diffusion commit [960b623](https://github.com/sd-webui/stable-diffusion/commit/960b623acdef3b9a14454550cc68ad04e8d531a3) and textual inversion [08f9b50](https://github.com/hlky/sd-enable-textual-inversion/commit/08f9b5046552d17cf7327b30a98410222741b070). 
I replaced the contents of the main repository folder with the ti one and overwrote when needed. Checked that the README.md had changed to ensure it worked and then tried it out.

Please do check if you have time.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Linux

### Custom settings

```shell
I'm running through gradio.app
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by isademigod** [comment]
+1. You can imagine my confusion when I saw in the docs "upload your .pt file through the webui" and there was nowhere to do that
