### ISSUE TITLE
[Bug]: Docker compose broke with repo move

### ISSUE THREAD

**Issue by outlookhazy** [sd-webui/stable-diffusion-webui#720]
### What happened?

Looks like .env_docker didn't make it in the transition, this breaks the docker-compose build - had to add it back in manually to rebuild after redirecting the repo on my end

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by outlookhazy** [comment]
Actually, it looks like this is caused by .env_docker being in the .gitignore in the webui repo

**Comment by shayne** [comment]
Submitted #730

**Comment by outlookhazy** [comment]
The wiki instructions (if/when they're migrated from the old repo) will need to be modified to indicate that .env_docker.example should be copied to .env_docker prior to attempting to run the compose build since docker-compose.yaml is hard-coded to look for the latter, which will be missing on a fresh clone.

**Comment by outlookhazy** [comment]
I'm going to close this in favor of an issue dedicated to Docker documentation
