### ISSUE TITLE
[Bug]: Clicking on refresh after job finishes should pull up results of last job

### ISSUE THREAD

**Issue by DasWookie** [sd-webui/stable-diffusion-webui#722]
### What happened?

If you click on refresh after the job finishes, instead of showing you the results of the last job it instead clears the results and you get an error in webui.py output of:
Couldn't find job FuncKey(job_id=UUID('4968de4e-4c0d-4483-ab0e-5ff42e4dee19'), func=<function txt2img at 0x7f5350149d30>) in session "201aa3d84a8046268b62d9c845f932d4"

Sometimes it works as expected, but most times it wipes the images and throws the FuncKey message.

Running code as of #247: Commit [78ad3c3](https://github.com/sd-webui/stable-diffusion-webui/commit/78ad3c34454c554b186ec5bfb65830eeaf3a8796) pushed by [hlky](https://github.com/hlky)

This can be caused by a race condition of between when the job finishes and when the browser updates to show the full results. I had a long running job of 100 images, so had been clicking refresh now and again to get the latest results. As it just happened, I clicked refresh when the browser was starting to show the job had completed, so all of the results of the run were cleared and I got the "Couldn't find job" emitted by the webui.py script.

I was able to reproduce this with only 1 image tho. Expectation is to show the results of the last job that browser submitted.

To reproduce:
Launch the webui.py server script
Connect browser to the URL
Start a job with 1 image generation job
Wait for the image to generate to complete and browser to show results
Hit Refresh
Results clear and "Couldn't find job FuncKey" message is emitted by webui.py

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Relevant log output

```shell
(lsd) [wookie@alma9 ultimate-stable-diffusion]$ ./linux-setup.sh
Relauncher: Launching...
Found GFPGAN
Found RealESRGAN
Found LDSR
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
/home/cyber/miniconda3/envs/lsd/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in File, please remove them: {'source': 'upload'}
  warnings.warn(
Error: Port: 7860 is not open yet. Please wait, this may take upwards of 60 seconds...
Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
[MemMon] Recording max memory usage...

Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████| 45/45 [00:09<00:00,  4.59it/s]
[MemMon] Stopped recording.

Couldn't find job FuncKey(job_id=UUID('6ede44f0-7ad4-43ed-9c9f-08d7e93ac105'), func=<function txt2img at 0x7fe5a1e9dd30>) in session "201aa3d84a8046268b62d9c845f932d4"
Couldn't find job FuncKey(job_id=UUID('6ede44f0-7ad4-43ed-9c9f-08d7e93ac105'), func=<function txt2img at 0x7fe5a1e9dd30>) in session "201aa3d84a8046268b62d9c845f932d4"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cobryan05** [comment]
Yeah, that is kind of annoying. It frees the images from the server as soon as the final batch is loaded into the gallery. Otherwise when the user closes the browser the final batch will forever be in RAM on the server. However, memory is cheap, people aren't really hosting this for multiple users, and you can clear finished jobs from RAM in the maintenance panel... and it took me longer to write this paragraph than to fix the issue, so here you go:

https://github.com/sd-webui/stable-diffusion-webui/commit/6e3463a9b602271c6c03aac0d0ccde091b339eb0

but I have no idea what is going on with the branches right now in this repo, so am not even sure how I'd presently put this into a pull request. It's just a couple lines for you to manually edit, though.
