### ISSUE TITLE
[Bug]: Link to install docs broken

### ISSUE THREAD

**Issue by TimothyStiles** [sd-webui/stable-diffusion-webui#734]
### What happened?

Bug lead's to previous repos wiki which is now blank

https://github.com/sd-webui/stable-diffusion-webui/blob/58c92228cdd3c52dd7b5379c72714525ce1ca0f1/README.md?plain=1#L3

https://github.com/hlky/stable-diffusion/wiki/Installation

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ihmlsmh** [comment]
My luck that this happens now that im trying to install this -_-

**Comment by ZeroCool940711** [comment]
If you need help with anything you can come to the discord server for the repo and we will help you there, [this is the link](https://discord.gg/gyXNe4NySY) for the server.

**Comment by lzardy** [comment]
I posted an archive of the wiki to the Discussion board, but I will repost here for those wondering. [Link](https://web.archive.org/web/20220904230244/https://github.com/hlky/stable-diffusion/wiki/Installation)
Also, the wiki of this repository seems to have added an "Linux Automated Setup" page, may be worth looking at.

**Comment by Ihmlsmh** [comment]
Thank you for your guys help! :)

> I posted an archive of the wiki to the Discussion board, but I will repost here for those wondering. [Link](https://web.archive.org/web/20220904230244/https://github.com/hlky/stable-diffusion/wiki/Installation) Also, the wiki of this repository seems to have added an "Linux Automated Setup" page, may be worth looking at.



> If you need help with anything you can come to the discord server for the repo and we will help you there, [this is the link](https://discord.gg/gyXNe4NySY) for the server.

**Comment by bouiboui** [comment]
It's also available here: https://github.com/sd-webui/stable-diffusion/wiki/Installation

**Comment by GeorgiaM-honestly** [comment]
> I posted an archive of the wiki to the Discussion board, but I will repost here for those wondering. [Link](https://web.archive.org/web/20220904230244/https://github.com/hlky/stable-diffusion/wiki/Installation) Also, the wiki of this repository seems to have added an "Linux Automated Setup" page, may be worth looking at.

Smart idea! Here is the linux install version:

https://web.archive.org/web/20220904230148/https://github.com/hlky/stable-diffusion/wiki/Linux-Installation

**Comment by codedealer** [comment]
Fixed in #781 
Access installation guide here https://github.com/sd-webui/stable-diffusion-webui/wiki/INSTALLATION
