### ISSUE TITLE
[Repo Permissions]: Unauthorized users have all rights to modify, create or delete wiki pages

### ISSUE THREAD

**Issue by seriousm4x** [sd-webui/stable-diffusion-webui#758]
### What happened?

I just checked the repos wiki for install instructions and noticed an edit button on the footer for the wiki pages.

I tried to edit it and well... I was able to. This affects all wiki pages.

Please change the permissions that only authorized users can edit the wiki.

Some screenshots...
![2022-09-07 12_26_12](https://user-images.githubusercontent.com/23456686/188856363-8690e379-84c1-4b77-bb99-745d50dd9f92.png)
![2022-09-07 12_26_27](https://user-images.githubusercontent.com/23456686/188856373-56ea6ec6-bf69-465e-983a-87d8b67ffb3d.png)
![2022-09-07 12_26_39](https://user-images.githubusercontent.com/23456686/188856377-ca24d109-fcab-4573-92ba-edee2d502c77.png)

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seriousm4x** [comment]
apparently normal users can also create new wiki pages

https://github.com/sd-webui/stable-diffusion-webui/wiki/permission-test

**Comment by queequeq** [comment]
This is kind of serious because of the possibility of linking to malicious pages (e.g. there's an install script users are supposed to run).

@hlky @AUTOMATIC1111 @altryne or some of the other maintainers, please have a look at this.

**Comment by hlky** [comment]
Fixed, it's a nice idea in theory but in practice the concerns you've all raised are valid, so if anyone wants to add to the wiki you'll have to ask someone who can do it it for you.

**Comment by seriousm4x** [comment]
Thanks for changing it. If you could delete the page at https://github.com/sd-webui/stable-diffusion-webui/wiki/permission-test and delete the footer, then everything is back to what it was before :)
