### ISSUE TITLE
[Bug]: When clicking to upload to img2img or imglab, only jpg files are allowed

### ISSUE THREAD

**Issue by aaronsantiago** [sd-webui/stable-diffusion-webui#763]
### What happened?

The file selection menu only allows JPG to be selected, but dragging allows for other file types

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjisnow** [comment]
Odd, when selecting files I get a choice between "All Files" in the dropdown and custom files ".png, .gif, .jfif, .pjpeg, .jpeg, pjp, .jpg". When selecting "All Files" I can choose any other image file type. Maybe it's something specific to do the the Gradio Image widget?
