### ISSUE TITLE
[Bug]: latent-diffusion folder missing in SRC.

### ISSUE THREAD

**Issue by ZeroCool22** [sd-webui/stable-diffusion-webui#797]
### What happened?

A bug happened!

![Screenshot_1](https://user-images.githubusercontent.com/13344308/189001079-f4ea4aca-be96-42b9-9e3b-e9379d454361.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/13344308/189001090-330bb5bf-1372-4bc7-b6e2-1ce17e1b9a1b.jpg)

So, what i do i create the folder or...?

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kallamamran** [comment]
Rename "model last.cpkt" to "model.cpkt" and place that file and the "project.yaml" in the folder .src\**latent-diffusion**\**experiments**\**pretrained_models**
If you don't have those folders you need to manually create them.

**Comment by ZeroCool22** [comment]
> Rename "model last.cpkt" to "model.cpkt" and place that file and the "project.yaml" in the folder #YOUR-SD-MAINFOLDER#\src\latent-diffusion\experiments\pretrained_models" If you don't have those folders you need to manually create them.
> 
> ![image](https://user-images.githubusercontent.com/25354644/189055891-d48b371f-29f8-4169-bec0-70f81ae605da.png)

Yeah, i created them manually.
