### ISSUE TITLE
[Bug]: Loopback no longer seems to use the last image

### ISSUE THREAD

**Issue by SirProdigle** [sd-webui/stable-diffusion-webui#822]
### What happened?

Did a 250 run loopback from one unrelated image to "3d render of mario sat at a table" on 0.2 strength and 15 CFG and each render seems to be taking the base. Previously I would see a slow trend from the first image to the description, but these seems to be just repeating the variation on the initial image.

The Iteration count is 1/1 repeating (e.g 250 instances of 'Iteration: 1/1' which I imagine is the issue

TLDR loopback seems to be working on the original image in all cases

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████████████████████| 51/51 [00:12<00:00,  4.11it/s]
[MemMon] Recording max memory usage...

[MemMon] Stopped recording.

Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████████████████████| 51/51 [00:12<00:00,  4.15it/s]
[MemMon] Recording max memory usage...

[MemMon] Stopped recording.

Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████████████████████| 51/51 [00:12<00:00,  4.15it/s]
[MemMon] Recording max memory usage...

[MemMon] Stopped recording.

Iteration: 1/1
100%|██████████████████████████████████████████████████████████████████████████████████| 51/51 [00:12<00:00,  4.03it/s]
[MemMon] Stopped recording.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
When debugging loopback I encountered the very same thing but thought it's just debug commands messing with memory addresses. Would need further investigation.

**Comment by SirProdigle** [comment]
Went back to an older version and confirmed in the past it treats it as 1/250 then 2/250 iterations etc. Right now seems to queue 250 instances of 1 img2img iteration.

**Comment by codedealer** [comment]
@SirProdigle can you link the revision where it worked?

**Comment by SirProdigle** [comment]
Sadly not sure, shortly after the migration to this repo I think, downloaded as a raw zip

**Comment by SirProdigle** [comment]
Believe webui.py:1415 `n_iter=1` might be the issue. It's causing it to run in batches of 1, but simply setting it back to n_iter doesn't fix the problem either.

From what I can tell it *is* setting the next init_img to the last output image, but there's a lot of copying and correction with that image before it gets fed back in, so that could be it?

**Comment by codedealer** [comment]
`n_iter=1` is set correctly. And the resulting image is being fed back *but* that reference can indeed be overwritten somewhere and point to the first image instead. I spent like an hour trying to understand what happens to that ref and found no issues. 

If anyone else wants to tackle this we will gladly accept a PR.

**Comment by unnamedplugins** [comment]
@codedealer I made a PR that appears to address this issue.  Please take a look - https://github.com/sd-webui/stable-diffusion-webui/pull/1067

**Comment by codedealer** [comment]
@unnamedplugins I did, the PR is good but unrelated to this.
