### ISSUE TITLE
[Bug]: Attempting to use Img2Img simply stops the app

### ISSUE THREAD

**Issue by Anotic** [sd-webui/stable-diffusion-webui#833]
### What happened?

When I click generate on img2img no matter the text or image input, the app simply stops and the console just returns to the folder structure without any error message at all.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
To create a public link, set `share=True` in `launch()`.
[MemMon] Recording max memory usage...

Iteration: 1/1

  0%|          | 0/38 [00:01<?, ?it/s]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anotic** [comment]
I ran the update script before making this issue, and I was using all default settings when attempting to use img2img.

**Comment by codedealer** [comment]
Try disabling all the upscalers in the settings before pressing generate.

**Comment by Anotic** [comment]
Not sure how to do that, upscale images is turned off by default
![image](https://user-images.githubusercontent.com/67927828/189248313-23c7defc-510b-41d4-94a6-401819c53dcd.png)

**Comment by codedealer** [comment]
Your UI looks very outdated to me, please update by pulling into `master` branch.

**Comment by Anotic** [comment]
yeah, no idea what i originally cloned yesterday but i'm updating now, i'm assuming thats the issue and i'll close this if it works once ive finished updating

**Comment by Anotic** [comment]
all working now, my bad for being on an outdated version

**Comment by crisroxxxxx** [comment]
nigth
