### ISSUE TITLE
[Bug]: The Aspect Ratio Window on text-to-image doesn't work

### ISSUE THREAD

**Issue by Heathen** [sd-webui/stable-diffusion-webui#843]
### What happened?

Moving the sliders on img-to-img correctly updates the aspect ratio information box, but on text to image it doesn't.
![image](https://user-images.githubusercontent.com/474879/189171557-eedccb04-437b-48e7-9566-40d715c43420.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s0updev** [comment]
same

**Comment by JuanLagu** [comment]
This should be fixed with https://github.com/sd-webui/stable-diffusion-webui/commit/c37de9f04edc26f82e742aba71f1549ae88a048b

**Comment by Luux** [comment]
@JuanLagu In the current dev branch, you cannot specify the aspect ratio at all:
![image](https://user-images.githubusercontent.com/15156652/190616983-3e6468a0-08ee-455d-927f-79e9adae5aa0.png)

**Comment by JuanLagu** [comment]
Hi @Luux. Sorry about the confusion. The aspect ratio is not an input to specify the aspect ratio, but the result of the current width and height. You can't currently set the aspect ratio, it's just a info box.
We can only use multiples of 64 for the dimensions, so you can't get the specific aspect ratio you want.

**Comment by JuanLagu** [comment]
Hi @Heathen the fix has been added to master. I believe this issue can be closed now.
