### ISSUE TITLE
[Bug]: Missing crop options

### ISSUE THREAD

**Issue by Pixeledberry** [sd-webui/stable-diffusion-webui#844]
### What happened?

There used to be 3 different cropping options in the Img2Img tab labeled "just resize, crop and resize, resize and fill" that I found super useful. Were these intentionally removed or is this a bug on my end? I've attached screenshots.

as shown in README.md:
![image](https://user-images.githubusercontent.com/112102459/189172972-224a385d-ecbe-483d-a2ac-06ac8d6ff551.png)

current versions output:
![image](https://user-images.githubusercontent.com/112102459/189172776-ea14da2e-d461-4680-b584-ff8cc1870785.png)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by geowjm** [comment]
i have the same issue, did you find the solution??

**Comment by codedealer** [comment]
It's not a bug they were disabled because they weren't working reliably.

If you want to help you're welcome to submit a PR with a fix.
