### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rikabi89** [sd-webui/stable-diffusion-webui#855]
### What happened?

I get this error, I have placed the model in the relevant folder etc and LDSR+GFPGAN both work but not RealESRGAN

Relauncher: Launching...
Loaded GFPGAN
Error loading RealESRGAN:
Traceback (most recent call last):
  File "scripts/webui.py", line 346, in try_loading_RealESRGAN
    RealESRGAN = load_RealESRGAN(model_name) # TODO: Should try to load both models before giving up
  File "scripts/webui.py", line 327, in load_RealESRGAN
    instance = RealESRGANer(scale=2, model_path=model_path, model=RealESRGAN_models[model_name], pre_pad=0, half=not opt.no_half, device=torch.device(f'cuda:{opt.gpu}'))
TypeError: __init__() got an unexpected keyword argument 'device'

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Relevant log output

```shell
Relauncher: Launching...
Loaded GFPGAN
Error loading RealESRGAN:
Traceback (most recent call last):
  File "scripts/webui.py", line 346, in try_loading_RealESRGAN
    RealESRGAN = load_RealESRGAN(model_name) # TODO: Should try to load both models before giving up
  File "scripts/webui.py", line 327, in load_RealESRGAN
    instance = RealESRGANer(scale=2, model_path=model_path, model=RealESRGAN_models[model_name], pre_pad=0, half=not opt.no_half, device=torch.device(f'cuda:{opt.gpu}'))
TypeError: __init__() got an unexpected keyword argument 'device'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YosAwed** [comment]
"Error loading RealESRGAN" means you didn't install RealESRGAN properly.
Did you check the pre-trained models file like RealESRGAN_x4plus_anime_6B into the folder correctly?
