### ISSUE TITLE
[Bug]: webui install uses ldm environment name even if ldo is specified in environment.yaml

### ISSUE THREAD

**Issue by Jonseed** [sd-webui/stable-diffusion-webui#860]
### What happened?

I change the environment name to ldo in the environment.yaml file as noted is optional in the installation doc, and after running the webui install it still created the environment with name ldm. Maybe this is because webui.cmd has "set conda_env_name=ldm" at the top, so when the script executes the line to create the environment, it overrides the name assigned in the environment.yaml file.

### Version

0.0.1 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DasWookie** [comment]
Yeah, that would be expected. You have to change it in both places.

**Comment by Jonseed** [comment]
Then the installation doc should note that you have to change it in both places.

**Comment by Hafiidz** [comment]
Hmm, will try to look at this, should need to do it once

**Comment by Hafiidz** [comment]
PR raised for this, hopefully merged soon.

**Comment by codedealer** [comment]
This should be on master now thanks to @Hafiidz! Closing.
