### ISSUE TITLE
[Bug]: img2img: Denoising Strength slider bar is linked to Sampling Steps

### ISSUE THREAD

**Issue by snarkipus** [sd-webui/stable-diffusion-webui#863]
### What happened?

When using img2img, the number of sample timesteps doesn't reflect it's setting. The number reflects the denoising strength x 100.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codedealer** [comment]
The number of steps is counted as strength * selected number of sample steps rounded to lower integer.

**Comment by snarkipus** [comment]
Ah - I apologize for the issue, it was just an odd coincidence.

**Comment by Ehplodor** [comment]
Same issue here : https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/193#issue-1368016770

Closed because not originating from AUTOMATIC1111's fork. Advised to elevate the issue.

I am still unconvinced that this is a feature and not a bug

**Comment by codedealer** [comment]
It works as designed. Now whether that design is wrong or not is up to discussion (not in this issue though). The code works as intended.
