### ISSUE TITLE
[Bug]: 'fetch' is being used to get the response of a long running process

### ISSUE THREAD

**Issue by kyle-wendling** [sd-webui/stable-diffusion-webui#868]
### What happened?

First off, great project, and appreciate the excitement and fast dev in these crazy image-gen-gold-rush days.

Issue is WebUI is basically unusable w/ google Colab based SD due to using fundamentally wrong web tech.
 
WebUI apparently uses an HTTP 'fetch' to wait for results of the 'generate' events, this leaves a TCP connection open for longer than TCP is made to support. 'generate' results take far far longer than an HTTP 'fetch', and a TCP conn, is supposed to be kept open (300 ms is chrome default, ~10 sec is max)

Basically fetch and TCP don't work this way. 

Either Chrome or Colab times out the open TCP connect WebUI leaves hanging after exactly 1 min. So yeah, appreciate this project, but no, fetch is not the right way to do this, please fix.
<img width="1263" alt="Screen Shot 2022-09-08 at 11 54 19 PM" src="https://user-images.githubusercontent.com/6612416/189269073-4e01545b-b4a4-44d1-b2da-e4af40284618.png">

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Colab

### Relevant log output

```shell
Please see screens, thanks!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by outlookhazy** [comment]
I think this is probably more of a gradio thing, which this project is using for the UI.  
Regarding your concerns, unless I'm missing something - the ui is using websockets for those purposes, not http.  
I did some reverse engineering of the protocol the other day, and it appeared to be using a fetch request to that predict enpoint to establish a session ID, then it subsequently used a websocket connection with that session id to handle the actual transactions.

**Comment by kyle-wendling** [comment]
Hey, thanks for taking a look at  this, I didn't try to look into the stack of JS layers too closely (and am not an expert) to know at what layer the 'fetch' was called. I have no exp with gradio, but guessing it's a low-code stack, and if it doesn't offer a way to check for results in a more reasonable way, this prj would be basically stuck? Does gradio allow like a manual refresh via a user clicked button or something?

**Comment by outlookhazy** [comment]
I'm not well versed in the tools being used myself. Just letting you know anecdotally that on my system, that fetch to predict is near instantaneous. If you're hanging there, something is probably wrong - not just slow
I don't know what that would be

**Comment by kyle-wendling** [comment]
I took a look at the docs, looks like Gradio already has built in support for long running process, just need to switch it over:
"
Queuing
If your app expects heavy traffic, use the queue() method to control processing rate. This will queue up calls so only a certain number of requests are processed at a single time. Queueing uses websockets, which also prevent network timeouts, so you should use queueing if the inference time of your function is long (> 1min)."
