### ISSUE TITLE
[Bug]:  missing src folder?

### ISSUE THREAD

**Issue by droidlosan** [sd-webui/stable-diffusion-webui#884]
### What happened?

The last week I could install the repository fine but I can't find src folder right now.
Any help? Maybe I am seeing the wrong url? But it's https://github.com/sd-webui/stable-diffusion-webui/
Thank you!

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hafiidz** [comment]
After latest pull/clone, you will need to run webui.cmd which will helps to auto download files to src folders. You will need to follow detailed instructions at https://github.com/sd-webui/stable-diffusion-webui/wiki/Installation, let me know if you still stucked.

**Comment by aetherwu** [comment]
Remember, if you init src folder manually, webui.cmd would fail or keep spinning for pip install.

**Comment by levicki** [comment]
@aetherwu @Hafiidz The readme of your repository has instructions on how to add GFPGAN and other stuff. If those files and folders are created before running `webui.cmd` it will be indefinitely stuck on installing pip dependencies. Only after removing those files and folders from `src` the installation will be successful. I think it would be good if those instructions were removed from readme and put into wiki as a step coming after running `webui.cmd`.
