### ISSUE TITLE
[Bug]: (white)space in description input

### ISSUE THREAD

**Issue by iGadget73** [sd-webui/stable-diffusion-webui#903]
### What happened?

When trying to put a description in the input text field, on chrome it **_refuses to accept (white) spaces_**, works when copied into the field, but that's a pain in the a$$ 👎 

Occurs on all description input fields, also when switched to multiline. Chrome Mac & Windows

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by outlookhazy** [comment]
I can't duplicate this (Windows/Chrome)

**Comment by iGadget73** [comment]
> I can't duplicate this (Windows/Chrome)

But I can, on both OSs:

https://user-images.githubusercontent.com/13452875/189392107-ca903414-0740-42d3-ad68-4ed0e9fa1a1e.mov

**Comment by codedealer** [comment]
Update your local repo.

**Comment by icexuick** [comment]
I have the same

**Comment by dvsilch** [comment]
> Me too in Chrome, but can't duplicate in Edge.
> 
> ### **Browser**
> Chrome 106.0.5249.91 Edge 105.0.1343.53
> 
> ### **OS**
> Windows 11 21H2 22000.978

I think this is a gradio's bug because when running a gradio's demo with `gradio.Interface` that creating an inputfield, I can't input whitespace except copy&paste or type ASCII value of whitespace.
