### ISSUE TITLE
[Bug]: Values not loaded from config\webui

### ISSUE THREAD

**Issue by thedyze** [sd-webui/stable-diffusion-webui#907]
### What happened?

Did a new clone today, any changed values are not loaded from webui.yaml (or webui_streamlit.yaml)

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Firefox

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjisnow** [comment]
Should do, did you check that the directory in the script is read correctly? You could always check webui.py line 2161 where it loads your  webui.yaml, or webui_streamlit.py line 72 where it loads the webui_streamlit.yaml

**Comment by thedyze** [comment]
> Should do, did you check that the directory in the script is points to the correct location? You could always check webui.py line 2161 where it loads your webui.yaml, or webui_streamlit.py line 72 where it loads the webui_streamlit.yaml

After a new clone of the repository, everything is not working fine, don't know why it didn't work before

**Comment by jjisnow** [comment]
Could you quote some lines from any error messages given by the program?

**Comment by thedyze** [comment]
That was the weird part, there were no error messages.
Can not test it again sorry, deleted the old clone.
