### ISSUE TITLE
[Bug]: .cmd don't launch

### ISSUE THREAD

**Issue by Yrbashazar** [sd-webui/stable-diffusion-webui#920]
### What happened?

.cmd don't launch

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kwaad2** [comment]
Running it in the command prompt, I'm getting this error.

`> was unexpected at this time.`

**Comment by mykeehu** [comment]
Same here, under Windows

**Comment by DvST8x** [comment]
Same, here's a bit more details: 

/p first_line=   0<environment.yaml
> was unexpected at this time.

**Comment by codedealer** [comment]
@Hafiidz seems to be related to your changes in the cmd files

**Comment by mykeehu** [comment]
I've temporarily reverted to the original state, and added the new lines in a comment
```

:: copy over the first line from environment.yaml, e.g. name: ldm, and take the second word after splitting by ":" delimiter 
:: set /p first_line=< environment.yaml  
:: for /f "tokens=2 delims=:" %%i in ("%first_line%") do set untrimmed_conda_env_name=%%i
:: remove whitespaces
:: for /f "tokens=* delims= " %%a in ("%untrimmed_conda_env_name%") do set conda_env_name=%%a
:: echo Environment name is set as %conda_env_name% as per environment.yaml

set conda_env_name=ldo
```

**Comment by PxlCode** [comment]
starting again 👍

**Comment by Hafiidz** [comment]
I couldn't reproduce the error in my local PC, but there might be some differences in order execution. 
I am rewriting this to be more explicit with quotes below.

`set /p "first_line=" < "environment.yaml" ` can somebody with this problem test this for me. @PxlCode , @mykeehu , @DvST8x , @Yrbashazar .

Will send PR if this fully resolved the problem.

**Comment by Hafiidz** [comment]
Send a draft, appreciate everyone's help to test.

Please also share you OS version. I am quite curious on how this were to happen.

**Comment by entusiastaIA** [comment]
Hi there... I just made an account to try help with this. I am no programmer but I test things. I needed some time to understand that I had to edit webui.cmd instead of environment.yaml... so there you can see my (lack of) knowledge.

Any way. Copypasting @mykeehu lines ad the begining of webui.cmd allowed me to launch AI again and play.
Reverting to a fresh downloaded webui.cmd and changing @Hafiidz line kept the problem.

OS is Windows 10 Home

**Comment by entusiastaIA** [comment]
> @Hafiidz Thanks for your work on the fix but the draft has the same error.
> 
> I'm running Windows 11 10.0.25188.1000 The only thing that could be different about my setup that I can think of is Conda is on the C: drive and the SD files are on the D: drive.

I do Have Conda on C: and SD on K: too.

**Comment by Hafiidz** [comment]
Mine is also on different disk, so that shouldn't be the issue. 
Could you please share the full picture of the CMD?

@codedealer , could you please help to revert both #860 & #895 from master while I am doing more detailed check in the dev branch. Hard to fix something that I unfortunately couldn't reproduce. My sincerest apologies.

**Comment by Hafiidz** [comment]
`> was unexpected at this time.` To double confirm, the error code is `>` or `<` ya?

**Comment by entusiastaIA** [comment]
How do I know the error code? without reverting the changes cmd just opens and closes itself without telling anything.

With the whole picture do you mean the whole lines of code inside it?

**Comment by Hafiidz** [comment]
Please add `pause` to the line after.
For example, copy and replace the first 8 lines with this

`@echo off

:: copy over the first line from environment.yaml, e.g. name: ldm, and take the second word after splitting by ":" delimiter 
set /p "first_line="< "environment.yaml"
for /f "tokens=2 delims=:" %%i in ("%first_line%") do set untrimmed_conda_env_name=%%i
for /f "tokens=* delims= " %%a in ("%untrimmed_conda_env_name%") do set conda_env_name=%%a
echo Environment name is set as %conda_env_name% as per environment.yaml
pause`

**Comment by DvST8x** [comment]
@Hafiidz 

Hope this helps
https://i.imgur.com/7vAf2dG.jpg

**Comment by Hafiidz** [comment]
> @Hafiidz
> 
> Hope this helps [i.imgur.com/7vAf2dG.jpg](https://i.imgur.com/7vAf2dG.jpg)

Is it possible for you to try with this. 
```
@echo off

:: copy over the first line from environment.yaml, e.g. name: ldm, and take the second word after splitting by ":" delimiter 
set /p "first_line="< "environment.yaml"
for /f "tokens=2 delims=:" %%i in ("%first_line%") do set untrimmed_conda_env_name=%%i
for /f "tokens=* delims= " %%a in ("%untrimmed_conda_env_name%") do set conda_env_name=%%a
echo Environment name is set as %conda_env_name% as per environment.yaml
pause
```

**Comment by Hafiidz** [comment]
Weird that the wording changes to set /p first line = **0** <environment.yaml

Not sure where that comes from.

**Comment by Hafiidz** [comment]
And, you can just paste your screencap in the comment box here. I also just learn this yesterday. Github automatically upload picture here after a few seconds.

**Comment by DvST8x** [comment]
Same exact error with your last request.

**Comment by Hafiidz** [comment]
Is it possible for you to double click the webui.cmd instead of calling from another command line?
Curious if that plays any role.

Sorry for a lot of question. Couldn't really reproduce this myself unfortunately. Huhu.

**Comment by entusiastaIA** [comment]
On the contrary, thank you for developing this AI.

I usually double click cmd. There is only a little difference if I right click execute it as a administrator: It opens says some words and closes. gonna try read them in time...

Spec not found: invalid name, try the format user/package

haha took me 6 tries

**Comment by Hafiidz** [comment]
Really appreciate your hard work to help me test. This is collaborative Open Source work. I just help with external side part for now. Mostly other team members are doing the hard part.

Could you please try another option. 
`set /p "%%first_line=" < "environment.yaml"`

**Comment by entusiastaIA** [comment]
BTW, I was using this branch because of the deepfry problem: https://github.com/xaedes/stable-diffusion-webui/tree/mask-restore-665

But have downloaded the whole master branch to do the tests, there's no difference. The code reverted works the new code closes on opening

**Comment by Hafiidz** [comment]
And thanks to use for error reporting and testing. Every contribution helps.

**Comment by entusiastaIA** [comment]
For now is frozen there...

![Captura](https://user-images.githubusercontent.com/113212323/189447242-57ae2894-2fee-4a21-ad93-d39345079150.PNG)

**Comment by entusiastaIA** [comment]
![Captura](https://user-images.githubusercontent.com/113212323/189447303-b7915358-aa86-485d-9641-7932d6a57577.PNG)

**Comment by pozibrothers** [comment]
The problem is related to how newlines are treated in the `environment.yaml` file. I have git configured to change all newline characters to `LF` and it was causing the problem as the Windows script was not stopping the for each line loop when finding an LF character.

If anyone is having this issue, open the `environment.yaml` file in vscode, click on the lower right side on the `LF` text, change it to CRLF and save the file. Then run the `webui.cmd` command again.

**Comment by Hafiidz** [comment]
We will revert the changes for now. Will continue to debug this further before we restore the automated environment set.

> The problem is related to how newlines are treated in the `environment.yaml` file. I have git configured to change all newline characters to `LF` and it was causing the problem as the Windows script was not stopping the for each line loop when finding an LF character.
> 
> If anyone is having this issue, open the `environment.yaml` file in vscode, click on the lower right side on the `LF` text, change it to CRLF and save the file. Then run the `webui.cmd` command again.

Oh my god. Thanks!!! I think this is it. Able to reproduce the error. Will try to check the best way to handle this when restoring this feature.

**Comment by DvST8x** [comment]
Confirming @pozibrothers fix works.
I made the same change in Notepad++

Thanks, good job.

**Comment by entusiastaIA** [comment]
If I didn't understand a word of what he said is alright to revert for now or should I try to understand it?

Thanks by the way.

**Comment by Hafiidz** [comment]
> If I didn't understand a word of what he said is alright to revert for now or should I try to understand it?
> 
> Thanks by the way.

Are you in master branch? If so, just sync back to this master branch, the revert has been done there. If you are in dev, please perform fix by @mykeehu , i.e. manually revert the changes by commenting and adding the old line.

```
:: copy over the first line from environment.yaml, e.g. name: ldm, and take the second word after splitting by ":" delimiter 
:: set /p first_line=< environment.yaml  
:: for /f "tokens=2 delims=:" %%i in ("%first_line%") do set untrimmed_conda_env_name=%%i
:: remove whitespaces
:: for /f "tokens=* delims= " %%a in ("%untrimmed_conda_env_name%") do set conda_env_name=%%a
:: echo Environment name is set as %conda_env_name% as per environment.yaml

set conda_env_name=ldm
```

**Comment by Hafiidz** [comment]
Need to take some rest first. Will be off for the rest of the days.

**Comment by kwaad2** [comment]
> We will revert the changes for now. Will continue to debug this further before we restore the automated environment set.
> 
> > The problem is related to how newlines are treated in the `environment.yaml` file. I have git configured to change all newline characters to `LF` and it was causing the problem as the Windows script was not stopping the for each line loop when finding an LF character.
> > If anyone is having this issue, open the `environment.yaml` file in vscode, click on the lower right side on the `LF` text, change it to CRLF and save the file. Then run the `webui.cmd` command again.
> 
> Oh my god. Thanks!!! I think this is it. Able to reproduce the error. Will try to check the best way to handle this when restoring this feature.

Yes. I will confirm as well, this fixed it.

**Comment by DarkAndBlue** [comment]
https://stackoverflow.com/a/20631625
worked for me

So instead of:
```
::set /p first_line=< environment.yaml
```
this:
```
for /F "delims=" %%i in (environment.yaml) do (  
  set first_line=%%i
  goto BREAK1
)
:BREAK1
```

**Comment by Hafiidz** [comment]
> for /F "delims=" %%i in (environment.yaml) do (  
>   set first_line=%%i
>   goto BREAK1
> )
> :BREAK1

Awesome, will be sending a PR for this. Really appreciate your help @DarkAndBlue
