### ISSUE TITLE
[Bug]: SpecNotFound: Invalid name, try the format: user/package

### ISSUE THREAD

**Issue by swer2002** [sd-webui/stable-diffusion-webui#930]
### What happened?

I unchecked stable-version so I can use the latest features of your awesome app. It was fine like 2-3 days ago. Now it throws me an error SpecNotFound: Invalid name, try the format: user/package in the Environment setup section.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Where are you running the webui?

Colab

### Relevant log output

```shell
SpecNotFound: Invalid name, try the format: user/package
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hafiidz** [comment]
Could you please confirm if you're on master or dev branch.

Please refer to issue #920, could be the same issue.

Pull the latest version if on master. If dev branch, need to do manual changes as per step [here](https://github.com/sd-webui/stable-diffusion-webui/issues/920#issuecomment-1242505732)

**Comment by swer2002** [comment]
> Could you please confirm if you're on master or dev branch.
> 
> Please refer to issue #920, could be the same issue.
> 
> Pull the latest version if on master. If dev branch, need to do manual changes as per step [here](https://github.com/sd-webui/stable-diffusion-webui/issues/920#issuecomment-1242505732)

**Comment by swer2002** [comment]
Sorry, I have no idea what that means. All I know is that when you press the button, it works fine with the stable-version checked but not when you uncheck the box to run the latest features and all. That error is thrown.

**Comment by Hafiidz** [comment]
> Sorry, I have no idea what that means. All I know is that when you press the button, it works fine with the stable-version checked but not when you uncheck the box to run the latest features and all. That error is thrown.

Do you mind screenshotting which button. Just print screen/snip and paste in this comment box here. Unfortunately, I couldn't picture which area you are talking about. The error seems related to conda environment. Which was why I shared the link previously. Alternatively, have you perform git sync/pull to ensure you are in the latest version?
