### ISSUE TITLE
[Bug]: Textual inversion integration broken on dev branch

### ISSUE THREAD

**Issue by unnamedplugins** [sd-webui/stable-diffusion-webui#950]
### What happened?

When either:
* Using the code from here: https://github.com/hlky/sd-enable-textual-inversion
* Doing a manual merger of the intended updates from that code base to the dev branch at time of reporting (I can provide a branch if needed)

Clicking "Generate" on the txt2img UI enqueues a job in the job scheduler, but the job never starts.  Disabling the job scheduler provides the expected functionality.

The main culprit seems to be the change to `FrozenCLIPEmbedder.enocde` - specifically when changing it to:
```
    def encode(self, text, **kwargs):
        return self(text, **kwargs)
```
Adding the **kwargs argument seems to cause the problem.  I am unable to fully debug the issue myself, but as best I can tell the job scheduler takes a token then immediately executes `_pre_call_func` and then gets stuck on `job_info.token = self._get_job_token(block=True)`.  Hopefully that information is useful.

I have not tested this on the master branch.

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

```shell
--precision full --no-half (to get the trained embeddings.pt to avoid `Index put requires the source and destination dtypes match, got Half for the destination and Float for the source.` error)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Notloc** [comment]
It seem this issue might be resolved now, I'm able to use textual inversion on dev without issue.

However, this issue is where I learned I needed to add `--precision full --no-half` as launch args to make textual inversion work. I've seen no reference to these instructions anywhere else, they should probably get documented somewhere visible.
